### PR TITLE
Create Teams controller

### PR DESCRIPTION
**Pull request by pczarn**
This change is [Reviewable](https://reviewable.io/reviews/pczarn/gameroom-task/8)

### CODE REVIEW

**Comment by pczarn** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

_[app/helpers/teams_helper.rb, line 3 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSaogE8ZE1g-hlM1RZa:-KSaogE9hNd1LwIy-dCm:b3goj8z) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/helpers/teams_helper.rb#L3)):_

> ``` Ruby
> module TeamsHelper
>   def potential_member_ids_and_names(team)
>     User.pluck(:id, :name) - User.joins(:teams).where(teams: { id: team.id }).pluck(:id, :name)
> ```

How can I use one query for this entire method?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/8)_

**Comment by monttda** [comment]
Reviewed 3 of 25 files at r1, 2 of 7 files at r2, 1 of 12 files at r3, 1 of 3 files at r4.
Review status: 4 of 16 files reviewed at latest revision, 12 unresolved discussions.

---

_[app/controllers/teams_controller.rb, line 8 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeV1SjgegDgaIzxCyk:-KSeV1SjgegDgaIzxCyl:blpy1jo) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L8)):_

> ``` Ruby
> 
>   def create
>     @team = Team.new(team_params.merge(members: [current_user]))
> ```

So you are always adding the current  user to the team ??

---

_[app/controllers/teams_controller.rb, line 21 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeUumrC-ehFGNIaqMt:-KSeUumrC-ehFGNIaqMu:b-nso3ij) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L21)):_

> ``` Ruby
>   def index
>     @teams = Team.page(params[:page])
>     @team = Team.new
> ```

why a new team in the index view ?

---

_[app/controllers/teams_controller.rb, line 36 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeXFSukmZp7cD3NyX-:-KSeXFSukmZp7cD3NyX0:bg3zret) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L36)):_

> ``` Ruby
>   end
> 
>   def destroy
> ```

Any reason useful use case in which we destroy a team ?

---

_[app/controllers/teams_controller.rb, line 42 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeVXexDZCK05HJFuCI:-KSeVXexDZCK05HJFuCJ:bxmudo3) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L42)):_

> ``` Ruby
>   end
> 
>   def add_member
> ```

this mean altering team, do we need this ? you need to be altering teams or is better to have all possible teams in the db as they are used in the system ? 

---

_[app/controllers/teams_controller.rb, line 51 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeX_0WiPVb9ZqjAUXg:-KSeX_0WiPVb9ZqjAUXh:b-7sz2ns) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L51)):_

> ``` Ruby
>   end
> 
>   def remove_member
> ```

Same as before. why do we need this ?

---

_[app/controllers/teams_controller.rb, line 69 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeVT5cyEMMw_P48n-j:-KSeVT5cyEMMw_P48n-k:birgjfu) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L69)):_

> ``` Ruby
>   end
> 
>   def load_team_2
> ```

why a team 2 ???

---

_[app/controllers/teams_controller.rb, line 79 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeTk-H6Yn99gLib3X7:-KSeTk-H6Yn99gLib3X8:b-jei9ou) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L79)):_

> ``` Ruby
>   end
> 
>   def expect_team_owner!
> ```

Why do we want team owners?

---

_[app/models/team.rb, line 2 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeXkUwayadbvdV0L6q:-KSeXkUxkyeYYsXsQPqB:b-kiebfo) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/models/team.rb#L2)):_

> ``` Ruby
> class Team < ApplicationRecord
>   has_many :user_teams, dependent: :destroy
> ```

when does this happen if apparently you can't delete the owner user_team ?

---

_[app/models/team.rb, line 37 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeVpvutasR4SuYPqbv:-KSeVpvutasR4SuYPqbw:bekp5ar) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/models/team.rb#L37)):_

> ``` Ruby
>   end
> 
>   def this_and_related_teams
> ```

what are the related teams of a team ?

---

_[app/models/user_team.rb, line 6 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeVuRhIKy39eUCzECk:-KSeVuRhIKy39eUCzECl:b-o6d7f8) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/models/user_team.rb#L6)):_

> ``` Ruby
> 
>   enum role: {
>     regular: 0,
> ```

why do we need roles ?

---

_[app/controllers/matches_controller.rb, line 16 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSaUa-EvzL_hq63t-SX:-KSaUa-F1uEdSgjho-KW:b-oebwok) ([raw file](https://github.com/pczarn/gameroom-task/blob/742600dfd0268cdfa4ecb74145bc5d7da5eeaa71/app/controllers/matches_controller.rb#L16)):_

> ``` Ruby
> 
>   def index
>     @match = Match.new(played_at: Time.zone.now)
> ```

why a new match in the index ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/8)_

**Comment by monttda** [comment]
Review status: 4 of 16 files reviewed at latest revision, 13 unresolved discussions.

---

_[app/controllers/teams_controller.rb, line 63 at r5](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSegI7CZHXR98IylJap:-KSegI7D6wt8KfXvaMQC:b-te7bw5) ([raw file](https://github.com/pczarn/gameroom-task/blob/2594513fe17f89bad11288391b4c24db5b0cff03/app/controllers/teams_controller.rb#L63)):_

> ``` Ruby
> 
>   def load_team
>     @team = Team.find(params[:id] || params[:team_id])
> ```

why 2 possible ids???

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/8)_

**Comment by pczarn** [comment]
Review status: 2 of 11 files reviewed at latest revision, 13 unresolved discussions.

---

_[app/controllers/teams_controller.rb, line 8 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeV1SjgegDgaIzxCyk:-KSfhuCCB_W56F3LBKfA:b-7ql1td) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L8)):_
<details><summary>

<i>Previously, monttda (Daniel Montenegro) wrote…</i></summary>



> So you are always adding the current  user to the team ??
> </details>
> fixed

---

_[app/controllers/teams_controller.rb, line 21 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeUumrC-ehFGNIaqMt:-KSfhvcuD9McgfLKejaG:bx17fho) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L21)):_
<details><summary>

<i>Previously, monttda (Daniel Montenegro) wrote…</i></summary>



> why a new team in the index view ?
> </details>
> So that a new team can be created in the index view. There's no `new` view. Do you think having a view with 2 responsibilities is ok?

---

_[app/controllers/teams_controller.rb, line 36 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeXFSukmZp7cD3NyX-:-KSfi7A8CLrpHXhoRQUr:b-gqk187) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L36)):_
<details><summary>

<i>Previously, monttda (Daniel Montenegro) wrote…</i></summary>



> Any reason useful use case in which we destroy a team ?
> </details>
> no, not directly. fixed.

---

_[app/controllers/teams_controller.rb, line 42 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeVXexDZCK05HJFuCI:-KSfi6lPkmb5LceIaEHZ:b-7ql1td) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L42)):_
<details><summary>

<i>Previously, monttda (Daniel Montenegro) wrote…</i></summary>



> this mean altering team, do we need this ? you need to be altering teams or is better to have all possible teams in the db as they are used in the system ? 
> </details>
> fixed

---

_[app/controllers/teams_controller.rb, line 51 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeX_0WiPVb9ZqjAUXg:-KSfjLvi3sEesxdqb43I:b-hfpv0l) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L51)):_
<details><summary>

<i>Previously, monttda (Daniel Montenegro) wrote…</i></summary>



> Same as before. why do we need this ?
> </details>
> removed

---

_[app/controllers/teams_controller.rb, line 69 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeVT5cyEMMw_P48n-j:-KSfjNCq4ZV6W5tebycO:b-hfpv0l) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L69)):_
<details><summary>

<i>Previously, monttda (Daniel Montenegro) wrote…</i></summary>



> why a team 2 ???
> </details>
> removed

---

_[app/controllers/teams_controller.rb, line 79 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeTk-H6Yn99gLib3X7:-KSfiOGrhJUEYc1Ut6YC:b4y2yj7) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L79)):_
<details><summary>

<i>Previously, monttda (Daniel Montenegro) wrote…</i></summary>



> Why do we want team owners?
> </details>
> Not anymore. Fixed

---

_[app/controllers/teams_controller.rb, line 63 at r5](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSegI7CZHXR98IylJap:-KSfhW67Xfty0Lnm7h_4:bha3wa4) ([raw file](https://github.com/pczarn/gameroom-task/blob/2594513fe17f89bad11288391b4c24db5b0cff03/app/controllers/teams_controller.rb#L63)):_
<details><summary>

<i>Previously, monttda (Daniel Montenegro) wrote…</i></summary>



> why 2 possible ids???
> </details>
> There were additional actions e.g. `add_member` which was routed at `/teams/:team_id/add_member`

---

_[app/models/team.rb, line 2 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeXkUwayadbvdV0L6q:-KSfivb9mG2b87xU4bQF:b4y2yj7) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/models/team.rb#L2)):_
<details><summary>

<i>Previously, monttda (Daniel Montenegro) wrote…</i></summary>



> when does this happen if apparently you can't delete the owner user_team ?
> </details>
> Not anymore. Fixed

---

_[app/models/team.rb, line 37 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeVpvutasR4SuYPqbv:-KSfioo1cPUjX51-_3ta:bo0su9) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/models/team.rb#L37)):_
<details><summary>

<i>Previously, monttda (Daniel Montenegro) wrote…</i></summary>



> what are the related teams of a team ?
> </details>
> Related teams are teams that share some members.

---

_[app/models/user_team.rb, line 6 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeVuRhIKy39eUCzECk:-KSfiWpZEiaacLVa-P08:b5fodir) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/models/user_team.rb#L6)):_
<details><summary>

<i>Previously, monttda (Daniel Montenegro) wrote…</i></summary>



> why do we need roles ?
> </details>
> Not anymore. fixed

---

_[app/controllers/matches_controller.rb, line 16 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSaUa-EvzL_hq63t-SX:-KSficiWNvrc9oUmEri3:bd7s5vp) ([raw file](https://github.com/pczarn/gameroom-task/blob/742600dfd0268cdfa4ecb74145bc5d7da5eeaa71/app/controllers/matches_controller.rb#L16)):_
<details><summary>

<i>Previously, monttda (Daniel Montenegro) wrote…</i></summary>



> why a new match in the index ?
> </details>
> Same reason as having a new team in the team index.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/8)_

**Comment by monttda** [comment]
Review status: 2 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

_[app/controllers/teams_controller.rb, line 21 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSeUumrC-ehFGNIaqMt:-KSjuuFFLE3a_BEPOMSd:b-un81px) ([raw file](https://github.com/pczarn/gameroom-task/blob/422bfd6fb8737ec9c12cf02ed4500e9a83bf6988/app/controllers/teams_controller.rb#L21)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> So that a new team can be created in the index view. There's no `new` view. Do you think having a view with 2 responsibilities is ok?
> </details>
> we can live with that for now (not the best idea  probably) but we will get to that more into the JS part since you will have to deal with requests

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/8)_

**Comment by mskv** [comment]
Reviewed 2 of 25 files at r1, 2 of 12 files at r3, 5 of 11 files at r6.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

_[app/views/teams/_display_short.html.erb, line 6 at r7](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSkTFCVTz28HHjIXwSC:-KSkTFCVTz28HHjIXwSD:bj6g1nv) ([raw file](https://github.com/pczarn/gameroom-task/blob/8ebd70b70ede22240aa92791ffe8f0034a95c08c/app/views/teams/_display_short.html.erb#L6)):_

> ``` erb
> with <%= team.members.count %> members
> 
> <%= link_to "(edit)", edit_team_path(team) %>
> ```

I've heard that you decided not to allow editing of a team.

From what I understand right now teams have a role more like a "lineup" or "roster". And they should be persisted per-tournament and never edited later for the sake of statistics. In the future we might divide the responsibility of defining a collection of users and identifying a team, but for now we should stay with just "unchangeable collection of users".

So maybe let's remove the edit and update links and actions? Or do you prefer to keep it?

At least if we want to edit a team, we should make sure it's not used in any tournament already.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/8)_

**Comment by mskv** [comment]
Reviewed 1 of 11 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/8)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[app/views/teams/_display_short.html.erb, line 6 at r7](https://reviewable.io:443/reviews/pczarn/gameroom-task/8#-KSkTFCVTz28HHjIXwSC:-KSkWAYTMHKzyC8MUm4M:b5ax97j) ([raw file](https://github.com/pczarn/gameroom-task/blob/8ebd70b70ede22240aa92791ffe8f0034a95c08c/app/views/teams/_display_short.html.erb#L6)):_
<details><summary>

<i>Previously, mskv (Michał Podwórny) wrote…</i></summary>



> I've heard that you decided not to allow editing of a team.
> 
> From what I understand right now teams have a role more like a "lineup" or "roster". And they should be persisted per-tournament and never edited later for the sake of statistics. In the future we might divide the responsibility of defining a collection of users and identifying a team, but for now we should stay with just "unchangeable collection of users".
> 
> So maybe let's remove the edit and update links and actions? Or do you prefer to keep it?
> 
> At least if we want to edit a team, we should make sure it's not used in any tournament already.
> </details>
> Yes. I prefer to keep editing the team name. That shouldn't affect statistics or anything else.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/8)_

**Pull request merged**
