### PR TITLE
Improve API code

### PR DESCRIPTION
**Pull request by pczarn**
This change is [Reviewable](https://reviewable.io/reviews/pczarn/gameroom-task/20)

### CODE REVIEW

**Comment by kapone89** [comment]
Reviewed 8 of 36 files at r1.
Review status: 8 of 35 files reviewed at latest revision, 1 unresolved discussion.

---

_[Gemfile, line 67 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVz9oReerUWlnjxWmIC:-KVz9oReerUWlnjxWmID:bcg8u07) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/Gemfile#L67)):_

> ``` Ruby
> gem "rack-cors", "~> 0.4", require: "rack/cors"
> 
> # For controllers
> ```

this description is too general

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by kapone89** [comment]
Reviewed 10 of 36 files at r1.
Review status: 15 of 35 files reviewed at latest revision, 3 unresolved discussions.

---

_[app/repositories/teams_repository.rb, line 2 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVzFr7NmbM5xPhaehKv:-KVzFr7OYpOBluvnIbdA:bos2m3d) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/app/repositories/teams_repository.rb#L2)):_

> ``` Ruby
> class TeamsRepository
>   def teams
> ```

You can call this method just "fetch". The same in other repositories

---

_[app/repositories/users_repository.rb, line 3 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVzGEdYXTg3tV95-CVP:-KVzGEdYXTg3tV95-CVQ:b-jw4n15) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/app/repositories/users_repository.rb#L3)):_

> ``` Ruby
> class UsersRepository
>   def users
>     User.all.select(:id, :name, :email, :role)
> ```

Selecting columns is useful when you have a lot of columns and returns a lot of rows and want to optimize query a bit. But it's not necessary here I think.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by kapone89** [comment]
Reviewed 2 of 36 files at r1.
Review status: 17 of 35 files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by kapone89** [comment]
Reviewed 2 of 36 files at r1.
Review status: 19 of 35 files reviewed at latest revision, 4 unresolved discussions.

---

_[Guardfile, line 35 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVzO-Y9HHW9gemEAQ_a:-KVzO-YAEeGKn-MmBRBO:bqqrpzo) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/Guardfile#L35)):_

> ``` Ruby
>   watch(%r{^app/controllers/api/v1/(.+)_controller\.rb$}) do |m|
>     [
>       rspec.spec.call("controllers/#{m[1]}_controller"),
> ```

Please put this specs into spec/controller/api/v1 dir

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by kapone89** [comment]
Review status: 19 of 35 files reviewed at latest revision, 5 unresolved discussions.

---

_[app/controllers/api/v1/friendly_matches_controller.rb, line 23 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVzOUTbIhvT7OUncyl6:-KVzOUTc8D0gYyKDRkV8:b-9hwcar) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/app/controllers/api/v1/friendly_matches_controller.rb#L23)):_

> ``` Ruby
> 
>       def update
>         service = FinishMatch.new(friendly_match, params: friendly_match_params)
> ```

Updating and finishing match should be separated into 2 methods

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by kapone89** [comment]
Reviewed 4 of 36 files at r1.
Review status: 23 of 35 files reviewed at latest revision, 7 unresolved discussions.

---

_[app/services/create_or_reuse_team.rb, line 9 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVzPLYxpA_Z-O4RU0LQ:-KVzPLYxpA_Z-O4RU0LR:bbupul2) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/app/services/create_or_reuse_team.rb#L9)):_

> ``` Ruby
>     team = Team.new(@params)
>     member_ids = team.member_ids.sort
>     reused = Team.joins(:users).group(:id).having("array_agg(users.id) = ARRAY[?]", member_ids)[0]
> ```

In postgres you can do "order by" inside aggregation functions. In this case you should do that.

---

_[db/seeds.rb, line 285 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVzPg7i63mk9A3XmXO6:-KVzPg7i63mk9A3XmXO7:b-efhw41) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/db/seeds.rb#L285)):_

> ``` Ruby
> Round.create(
>   tournament: ufc_september,
>   matches: ufc_september_rounds[1],
> ```

Generally, these seeds are ok, but you can think about using FactoryGirl here in the future.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by pczarn** [comment]
Review status: 23 of 35 files reviewed at latest revision, 7 unresolved discussions.

---

_[Gemfile, line 67 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVz9oReerUWlnjxWmIC:-KVzQyxpoNjCsvqqgIVK:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/Gemfile#L67)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> this description is too general
> </details>
> Done

---

_[Guardfile, line 35 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVzO-Y9HHW9gemEAQ_a:-KVzwyqw3B65vXIX9hT6:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/Guardfile#L35)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Please put this specs into spec/controller/api/v1 dir
> </details>
> Done

---

_[app/controllers/api/v1/friendly_matches_controller.rb, line 23 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVzOUTbIhvT7OUncyl6:-KVzyOTzTDfWJpMRxq5p:b-bupx9w) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/app/controllers/api/v1/friendly_matches_controller.rb#L23)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Updating and finishing match should be separated into 2 methods
> </details>
> Do you mean two separate services? I'll think about that

---

_[app/repositories/teams_repository.rb, line 2 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVzFr7NmbM5xPhaehKv:-KVzQo5S74zsLIeJ2WTL:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/app/repositories/teams_repository.rb#L2)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> You can call this method just "fetch". The same in other repositories
> </details>
> Done

---

_[app/repositories/users_repository.rb, line 3 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVzGEdYXTg3tV95-CVP:-KVzQmOYGsdXKvJGF1bf:b-j4xibe) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/app/repositories/users_repository.rb#L3)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Selecting columns is useful when you have a lot of columns and returns a lot of rows and want to optimize query a bit. But it's not necessary here I think.
> </details>
> Done, removed it

---

_[app/services/create_or_reuse_team.rb, line 9 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVzPLYxpA_Z-O4RU0LQ:-KVzyHm_xrNuIjrS97II:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/app/services/create_or_reuse_team.rb#L9)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> In postgres you can do "order by" inside aggregation functions. In this case you should do that.
> </details>
> Done

---

_[db/seeds.rb, line 285 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVzPg7i63mk9A3XmXO6:-KVzQWF4dQ0q4OmpFheR:b-e8l7gt) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/db/seeds.rb#L285)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Generally, these seeds are ok, but you can think about using FactoryGirl here in the future.
> </details>
> Ok. Every mentor has a different opinion about such small things

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by pczarn** [comment]
Review status: 19 of 38 files reviewed at latest revision, 7 unresolved discussions.

---

_[app/controllers/api/v1/friendly_matches_controller.rb, line 23 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KVzOUTbIhvT7OUncyl6:-KW2Ik1qzEkG_z70S5fg:b8f61mv) ([raw file](https://github.com/pczarn/gameroom-task/blob/053b120c502996a2764ef97a3ff51bc7c7bb4aca/app/controllers/api/v1/friendly_matches_controller.rb#L23)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> Do you mean two separate services? I'll think about that
> </details>
> I see. Updating a friendly match is so simple it doesn't need a service.

I renamed FinishMatch to UpdateMatch. It's still the same service though.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by kapone89** [comment]
Reviewed 2 of 39 files at r1, 21 of 25 files at r2, 11 of 12 files at r3.
Review status: 37 of 40 files reviewed at latest revision, 1 unresolved discussion.

---

_[app/services/update_match.rb, line 100 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW3yoeD6pPKaTmCFNt9:-KW3yoeD6pPKaTmCFNtA:b-bdh71m) ([raw file](https://github.com/pczarn/gameroom-task/blob/64f35ca1f255778d1586a99fac855e5a631534fc/app/services/update_match.rb#L100)):_

> ``` Ruby
> end
> 
> class CreateNextMatch
> ```

Please move each class to separate files

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by kapone89** [comment]
Review status: 37 of 40 files reviewed at latest revision, 2 unresolved discussions.

---

_[app/controllers/api/v1/lineups_controller.rb, line 11 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW3zjNwnSWM5mb_RSQ4:-KW3zjNwnSWM5mb_RSQ5:be8u9co) ([raw file](https://github.com/pczarn/gameroom-task/blob/64f35ca1f255778d1586a99fac855e5a631534fc/app/controllers/api/v1/lineups_controller.rb#L11)):_

> ``` Ruby
> 
>       def create
>         authorize tournament.team_tournaments.build(team: create_team)
> ```

Please move it to the service

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by kapone89** [comment]
Reviewed 1 of 25 files at r2, 1 of 12 files at r3.
Review status: 38 of 40 files reviewed at latest revision, 4 unresolved discussions.

---

_[app/controllers/api/v1/lineups_controller.rb, line 37 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW40PxrfGXGw-POMzOz:-KW40PxsmAMuDNALiELu:b-x1nlq5) ([raw file](https://github.com/pczarn/gameroom-task/blob/64f35ca1f255778d1586a99fac855e5a631534fc/app/controllers/api/v1/lineups_controller.rb#L37)):_

> ``` Ruby
>       def authorize_update(model)
>         if leaving?
>           authorize model, :leave?
> ```

Separate controller actions for joining, leaving and updating would be much more cleaner.

---

_[spec/controllers/api/v1/friendly_matches_controller_spec.rb, line 55 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW4-mXFz0k_4EekFciF:-KW4-mXGrZfKFDoiJzR6:b-sjtbqp) ([raw file](https://github.com/pczarn/gameroom-task/blob/64f35ca1f255778d1586a99fac855e5a631534fc/spec/controllers/api/v1/friendly_matches_controller_spec.rb#L55)):_

> ``` Ruby
>       it "shows both matches" do
>         get_index
>         expect(response_match_ids).to include(my_match.id, other_match.id)
> ```

You can use match_array to be sure that there are only given ids.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by pczarn** [comment]
Review status: 38 of 40 files reviewed at latest revision, 4 unresolved discussions.

---

_[app/controllers/api/v1/lineups_controller.rb, line 11 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW3zjNwnSWM5mb_RSQ4:-KW7bPge6Wsb93-_LA4z:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/64f35ca1f255778d1586a99fac855e5a631534fc/app/controllers/api/v1/lineups_controller.rb#L11)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Please move it to the service
> </details>
> Done

---

_[app/controllers/api/v1/lineups_controller.rb, line 37 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW40PxrfGXGw-POMzOz:-KW7TQ76p8qTc5u2sAVM:bht2bq1) ([raw file](https://github.com/pczarn/gameroom-task/blob/64f35ca1f255778d1586a99fac855e5a631534fc/app/controllers/api/v1/lineups_controller.rb#L37)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Separate controller actions for joining, leaving and updating would be much more cleaner.
> </details>
> I had separate actions before, and they're not much cleaner, in the frontend code too. So having one action or separate actions is just different, both with downsides and advantages

---

_[app/services/update_match.rb, line 100 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW3yoeD6pPKaTmCFNt9:-KW7aZbz0td_RTMX9aYW:b-cr5s5f) ([raw file](https://github.com/pczarn/gameroom-task/blob/64f35ca1f255778d1586a99fac855e5a631534fc/app/services/update_match.rb#L100)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Please move each class to separate files
> </details>
> Done. Maybe I should make a new directory for these files, because these service classes will be used by another service only

---

_[spec/controllers/api/v1/friendly_matches_controller_spec.rb, line 55 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW4-mXFz0k_4EekFciF:-KW7TKCFeJHy1K_3HArO:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/64f35ca1f255778d1586a99fac855e5a631534fc/spec/controllers/api/v1/friendly_matches_controller_spec.rb#L55)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> You can use match_array to be sure that there are only given ids.
> </details>
> Done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by kapone89** [comment]
Reviewed 1 of 25 files at r2, 2 of 12 files at r3, 12 of 12 files at r4.
Review status: 46 of 47 files reviewed at latest revision, 1 unresolved discussion.

---

_[app/services/update_match_attributes.rb, line 1 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW8lCRbdcUDbkedqEv-:-KW8lCRbdcUDbkedqEv0:b8q8tk) ([raw file](https://github.com/pczarn/gameroom-task/blob/d62fe0d94909aff39735ec34a25185294da0c6c5/app/services/update_match_attributes.rb#L1)):_

> ``` Ruby
> class UpdateMatchAttributes
> ```

For such a simple case you don't need service, but it can stay ;-)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by kapone89** [comment]
Reviewed 1 of 39 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[app/controllers/api/v1/lineups_controller.rb, line 37 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW40PxrfGXGw-POMzOz:-KW8oMzd4OqFNshv2Tnm:b-896fix) ([raw file](https://github.com/pczarn/gameroom-task/blob/64f35ca1f255778d1586a99fac855e5a631534fc/app/controllers/api/v1/lineups_controller.rb#L37)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> I had separate actions before, and they're not much cleaner, in the frontend code too. So having one action or separate actions is just different, both with downsides and advantages
> </details>
> Done.

---

_[app/services/update_lineup.rb, line 1 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW8oRNtH-41bA8wYlvQ:-KW8oRNtH-41bA8wYlvR:boczvxc) ([raw file](https://github.com/pczarn/gameroom-task/blob/d62fe0d94909aff39735ec34a25185294da0c6c5/app/services/update_lineup.rb#L1)):_

> ``` Ruby
> class UpdateLineup
> ```

`update` action in controller and this service are to general too many things are happening here.  Replacing and destroying for friendly matches and tournaments should be separeted into 4 separete services with simple login. If you need to share some logic between them, you can create superclass. And you should have separate endpoints.

But exceptionally you don't have to do it. Kamila asked me to speed up review a bit so you can leave it. But you should know that it would not pass review normally ;-)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[app/services/update_lineup.rb, line 1 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW8oRNtH-41bA8wYlvQ:-KW8rotuRIrkKHZUbCOp:bi1g902) ([raw file](https://github.com/pczarn/gameroom-task/blob/d62fe0d94909aff39735ec34a25185294da0c6c5/app/services/update_lineup.rb#L1)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> `update` action in controller and this service are to general too many things are happening here.  Replacing and destroying for friendly matches and tournaments should be separeted into 4 separete services with simple login. If you need to share some logic between them, you can create superclass. And you should have separate endpoints.
> 
> But exceptionally you don't have to do it. Kamila asked me to speed up review a bit so you can leave it. But you should know that it would not pass review normally ;-)
> </details>
> Ok. In which file should I put this superclass? It's not going to be a complete service.

I'll change it to pass review if you tell me how to do it right ;)

---

_[app/services/update_match_attributes.rb, line 1 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW8lCRbdcUDbkedqEv-:-KW8rWAw7Qee04jA2-wU:bdv2qd1) ([raw file](https://github.com/pczarn/gameroom-task/blob/d62fe0d94909aff39735ec34a25185294da0c6c5/app/services/update_match_attributes.rb#L1)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> For such a simple case you don't need service, but it can stay ;-)
> </details>
> I need this class to use it in UpdateLineup service

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by kapone89** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[app/services/update_lineup.rb, line 1 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW8oRNtH-41bA8wYlvQ:-KW8tW2U6_NpWw7wCKiU:b9md91o) ([raw file](https://github.com/pczarn/gameroom-task/blob/d62fe0d94909aff39735ec34a25185294da0c6c5/app/services/update_lineup.rb#L1)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> Ok. In which file should I put this superclass? It's not going to be a complete service.
> 
> I'll change it to pass review if you tell me how to do it right ;)
> </details>
> Not all classes in app/services needs to be complete service. You can put superclass there.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by pczarn** [comment]
Review status: 45 of 51 files reviewed at latest revision, 1 unresolved discussion.

---

_[app/services/update_lineup.rb, line 1 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/20#-KW8oRNtH-41bA8wYlvQ:-KWCYFb3wcOKOVtsU15n:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/d62fe0d94909aff39735ec34a25185294da0c6c5/app/services/update_lineup.rb#L1)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Not all classes in app/services needs to be complete service. You can put superclass there.
> </details>
> Done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Comment by kapone89** [comment]
Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/20)_

**Pull request merged**
