### PR TITLE
Create Matches controller

### PR DESCRIPTION
**Pull request by pczarn**
This change is [Reviewable](https://reviewable.io/reviews/pczarn/gameroom-task/3)

### CODE REVIEW

**Comment by jotka87** [comment]
Reviewed 9 of 15 files at r1, 5 of 5 files at r2.
Review status: 14 of 15 files reviewed at latest revision, 11 unresolved discussions.

---

_[app/controllers/matches_controller.rb, line 6 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRZ41_eJcbG7rRJNh-m:-KRZ41_eJcbG7rRJNh-n:b-lzxvai) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/app/controllers/matches_controller.rb#L6)):_

> ``` Ruby
>   def create
>     @match = Match.create(match_params)
>     if @match.save
> ```

saving the record two times, should be:

``` ruby
@match = Match.new(match_params)
if @match.save
...
```

---

_[app/controllers/matches_controller.rb, line 10 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRcPFFobM3RnnBuM03-:-KRcPFFpUBsqWxQ7zCUO:bp4feyz) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/app/controllers/matches_controller.rb#L10)):_

> ``` Ruby
>     else
>       flash[:error] = @match.errors.full_messages
>       redirect_to action: :index
> ```

you should use redirect only after saving the record, if the record is invalid you should use render so user won't loose the data that he provided.

---

_[app/controllers/matches_controller.rb, line 15 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRcQzQ_80vBg7Pl_uJz:-KRcQzQ_80vBg7Pl_uK-:b9dnp9s) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/app/controllers/matches_controller.rb#L15)):_

> ``` Ruby
> 
>   def index
>     sanitize_param
> ```

You don't need to do that, it will work with passed string.

---

_[app/controllers/matches_controller.rb, line 16 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRcO9aN88akYCihuV0V:-KRcO9aN88akYCihuV0W:b-i0fjgg) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/app/controllers/matches_controller.rb#L16)):_

> ``` Ruby
>   def index
>     sanitize_param
>     @new_match = Match.new
> ```

It would be useful to initialize a match with current time, so user don't need to specify this.

---

_[app/controllers/matches_controller.rb, line 22 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRcOdug91lqE0XV2ep8:-KRcOdug91lqE0XV2ep9:b-68wq5n) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/app/controllers/matches_controller.rb#L22)):_

> ``` Ruby
>   end
> 
>   def show
> ```

I have a suggestion to get rid off `show` action - I think it's more useful if we can see and modify data at one time, so I would stick with `edit` action only. You are currently doing this by having a form inside a `show` template - this could be a little confusing. 

---

_[app/controllers/matches_controller.rb, line 27 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRcPTny-JMXWijzAjTm:-KRcPTnz2FNpf3g6bLPV:b-1p8ghf) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/app/controllers/matches_controller.rb#L27)):_

> ``` Ruby
>   def update
>     flash[:error] = @match.errors.full_messages unless @match.update(match_params)
>     redirect_to @match
> ```

similar as for `create` action - redirect after saving and render when invalid data provided.

---

_[app/views/matches/_display_short.html.erb, line 10 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRcU2Q32GK8RPm_6kMz:-KRcU2Q32GK8RPm_6kN-:b-ahmz5s) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/app/views/matches/_display_short.html.erb#L10)):_

> ``` erb
> <%= [match.teams_in_order[0].score, match.teams_in_order[1].score].join(":") %>
> at
> <%= time_tag match.played_at %>
> ```

That's actually the same as `_display_long` plus link - please make it more DRY.

---

_[app/views/matches/_edit.html.erb, line 5 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRcTPq2UsftuCpJ7L76:-KRcTPq2UsftuCpJ7L77:b5deawl) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/app/views/matches/_edit.html.erb#L5)):_

> ``` erb
> <fieldset>
>   <legend>The game</legend>
>   <% game_ids_and_names.map do |(id, name)| %>
> ```

`each` instead of `map`

---

_[app/views/matches/_edit.html.erb, line 30 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRcSrjbXzjBYJStJggC:-KRcSrjbXzjBYJStJggD:b-z2h7qt) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/app/views/matches/_edit.html.erb#L30)):_

> ``` erb
>     <%= f.number_field :team_two_score %>
> </fieldset>
> <%= f.submit "Submit" %>
> ```

Better name for this partial would be `_form`

---

_[spec/controllers/matches_controller_spec.rb, line 26 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRZ7tu3b-gYqbW_TIXZ:-KRZ7tu3b-gYqbW_TIX_:b4qsigd) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/spec/controllers/matches_controller_spec.rb#L26)):_

> ``` Ruby
>       end
> 
>       context "with a ?involving_user=ID parameter" do
> ```

description should be given as a understandable sentence, how about something like: "with an involving_user parameter passed"?

---

_[spec/controllers/matches_controller_spec.rb, line 40 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRbf_Tqd3xsBCEO57_0:-KRbf_TrNa0EsUT1d4_s:b-i6xtyz) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/spec/controllers/matches_controller_spec.rb#L40)):_

> ``` Ruby
>   end
> 
>   describe "#create" do
> ```

you can dry a little bit those tests by using `subject` and passing there the request call, for example:

``` ruby
describe "#create" do
  let(:match) { build(:match) }

  subject { post :create, params: { match: match.attributes } }

  it "succeeds" do
    expect(subject).to redirect_to(assigns(:match))
  end

  it "stores a new match" do
    expect { subject }.to change(Match, :count).by(1)
  end
  ...
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Comment by pczarn** [comment]
Review status: 14 of 15 files reviewed at latest revision, 11 unresolved discussions.

---

_[app/controllers/matches_controller.rb, line 22 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRcOdug91lqE0XV2ep8:-KRcjFMPX8GlhJQ2-jO_:b-nn1p8) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/app/controllers/matches_controller.rb#L22)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> I have a suggestion to get rid off `show` action - I think it's more useful if we can see and modify data at one time, so I would stick with `edit` action only. You are currently doing this by having a form inside a `show` template - this could be a little confusing. 
> </details>
> Ok. I'm going to route to `edit` with `get "/matches/:id"` in routes. I think you wanted to route it in some other way

---

_[app/views/matches/_display_short.html.erb, line 10 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRcU2Q32GK8RPm_6kMz:-KRck0Es_WwNA3_x9Y_q:b-8kxic2) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/app/views/matches/_display_short.html.erb#L10)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> That's actually the same as `_display_long` plus link - please make it more DRY.
> </details>
> I'm changing `_display_long` so they're not the same anymore.

---

_[spec/controllers/matches_controller_spec.rb, line 40 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRbf_Tqd3xsBCEO57_0:-KRcl8PNV3vhp7X8tuRI:b5tsllj) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/spec/controllers/matches_controller_spec.rb#L40)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> you can dry a little bit those tests by using `subject` and passing there the request call, for example:
> 
> ``` ruby
> describe "#create" do
>   let(:match) { build(:match) }
> 
>   subject { post :create, params: { match: match.attributes } }
> 
>   it "succeeds" do
>     expect(subject).to redirect_to(assigns(:match))
>   end
> 
>   it "stores a new match" do
>     expect { subject }.to change(Match, :count).by(1)
>   end
>   ...
> ```
> 
> </details>
> rubocop gives me warnings that the subject is not named, but it's ok. I can name it.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Comment by jotka87** [comment]
Reviewed 11 of 12 files at r3.
Review status: 15 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

_[app/controllers/matches_controller.rb, line 22 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRcOdug91lqE0XV2ep8:-KRd-7mJX1weN5RKEjO4:buf587i) ([raw file](https://github.com/pczarn/gameroom-task/blob/0dfe88eaf10806508d9e5237a120ae4637f508a9/app/controllers/matches_controller.rb#L22)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> Ok. I'm going to route to `edit` with `get "/matches/:id"` in routes. I think you wanted to route it in some other way
> </details>
> there should not be any changes in `routes.rb` for `edit` action. The only thing we want to do is not to use `show` action and the behaviour for `edit` should stay the default way with the default url etc.

---

_[config/routes.rb, line 3 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRczDuGwqhZL48YEYkX:-KRczDuGwqhZL48YEYkY:b-oomm6t) ([raw file](https://github.com/pczarn/gameroom-task/blob/ca81402ca8746e72c88d6d0d78013bd465c8b018/config/routes.rb#L3)):_

> ``` Ruby
> Rails.application.routes.draw do
>   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
>   get "/matches/:id", to: "matches#edit", as: "match"
> ```

noooo don't do that, routes should stay the same, you only need:

``` ruby
resources :matches, except: [:show]
```

the rest should be properly handled in the controller

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Comment by pczarn** [comment]
Review status: 15 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

_[config/routes.rb, line 3 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRczDuGwqhZL48YEYkX:-KRd49CyZn6FukofPYFU:b-1qg7aj) ([raw file](https://github.com/pczarn/gameroom-task/blob/ca81402ca8746e72c88d6d0d78013bd465c8b018/config/routes.rb#L3)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> noooo don't do that, routes should stay the same, you only need:
> 
> ``` ruby
> resources :matches, except: [:show]
> ```
> 
> the rest should be properly handled in the controller
> </details>
> ok. done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Comment by jotka87** [comment]
Reviewed 1 of 12 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[app/models/match.rb, line 18 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRd5_ktJcBzYlmT5Ggl:-KRd5_ktJcBzYlmT5Ggm:b-9ao3hx) ([raw file](https://github.com/pczarn/gameroom-task/blob/ca81402ca8746e72c88d6d0d78013bd465c8b018/app/models/match.rb#L18)):_

> ``` Ruby
>   validate :no_repeated_members_across_teams
> 
>   def teams_in_order
> ```

you don't need that, more simpler way is to explicitly use the right teams and their scores in view, so in partial you will have:

``` ruby
<%= match.team_one.name %>
vs
<%= match.team_two.name %>
with score
<%= [match.team_one_score, match.team_two_score].join(":") %>
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[app/models/match.rb, line 18 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRd5_ktJcBzYlmT5Ggl:-KRd74JgbsPslZOoSbGd:b-v0t9hw) ([raw file](https://github.com/pczarn/gameroom-task/blob/ca81402ca8746e72c88d6d0d78013bd465c8b018/app/models/match.rb#L18)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> you don't need that, more simpler way is to explicitly use the right teams and their scores in view, so in partial you will have:
> 
> ``` ruby
> <%= match.team_one.name %>
> vs
> <%= match.team_two.name %>
> with score
> <%= [match.team_one_score, match.team_two_score].join(":") %>
> ```
> 
> </details>
> I'd like to have them ordered by score... so the winning team is `match.team_one_score > match.team_two_score ? match.team_one : match.team_two`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[app/models/match.rb, line 18 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRd5_ktJcBzYlmT5Ggl:-KRd7Zdn6tDn99jVJFPJ:bsjp6fv) ([raw file](https://github.com/pczarn/gameroom-task/blob/ca81402ca8746e72c88d6d0d78013bd465c8b018/app/models/match.rb#L18)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> I'd like to have them ordered by score... so the winning team is `match.team_one_score > match.team_two_score ? match.team_one : match.team_two`
> </details>
> and the winning team always appears first.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Comment by jotka87** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[app/models/match.rb, line 18 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRd5_ktJcBzYlmT5Ggl:-KRd7kVzh1FUwhuq_9te:b-24r7rz) ([raw file](https://github.com/pczarn/gameroom-task/blob/ca81402ca8746e72c88d6d0d78013bd465c8b018/app/models/match.rb#L18)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> and the winning team always appears first.
> </details>
> OK, but which team that would be? How would we know which score is assigned to which team?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Comment by jotka87** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[app/models/match.rb, line 18 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRd5_ktJcBzYlmT5Ggl:-KRd8YcevqkTgtLKyG2P:bl07jsc) ([raw file](https://github.com/pczarn/gameroom-task/blob/ca81402ca8746e72c88d6d0d78013bd465c8b018/app/models/match.rb#L18)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> OK, but which team that would be? How would we know which score is assigned to which team?
> </details>
> Ok, one sec, I might miss something

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Comment by jotka87** [comment]
Review status: 14 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

_[app/models/match.rb, line 18 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRd5_ktJcBzYlmT5Ggl:-KRdEnK8fQ1o5JaPwdop:blais8y) ([raw file](https://github.com/pczarn/gameroom-task/blob/ca81402ca8746e72c88d6d0d78013bd465c8b018/app/models/match.rb#L18)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> Ok, one sec, I might miss something
> </details>
> How about something like this:
> 
> ``` ruby
>   def winning_team
>     @winning_team ||= teams_in_order[0]
>   end
> ```

  def defeated_team
    @defeated_team ||= teams_in_order[1]
  end

  def teams
    @teams ||= [
      TeamInMatch.new(team_one.id, team_one.name, team_one_score),
      TeamInMatch.new(team_two.id, team_two.name, team_two_score),
    ]
  end

  def teams_in_order
    @teams_in_order ||= begin
      return team unless team_one_score && team_two_score
      team_one_score < team_two_score ? teams.reverse : team
    end
  end

```
And then using `match.winning_team` and `match.defeated_team` in the view?

Therefore it's more readable in the view what we're actually rendering.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)*
<!-- Sent from Reviewable.io -->
```

**Comment by jotka87** [comment]
Review status: 14 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

_[app/models/match.rb, line 18 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRd5_ktJcBzYlmT5Ggl:-KRdINHxmcLEu6X-lXOE:b-136frm) ([raw file](https://github.com/pczarn/gameroom-task/blob/ca81402ca8746e72c88d6d0d78013bd465c8b018/app/models/match.rb#L18)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> How about something like this:
> 
> ``` ruby
>   def winning_team
>     @winning_team ||= teams_in_order[0]
>   end
> 
>   def defeated_team
>     @defeated_team ||= teams_in_order[1]
>   end
> 
>   def teams
>     @teams ||= [
>       TeamInMatch.new(team_one.id, team_one.name, team_one_score),
>       TeamInMatch.new(team_two.id, team_two.name, team_two_score),
>     ]
>   end
> 
>   def teams_in_order
>     @teams_in_order ||= begin
>       return team unless team_one_score && team_two_score
>       team_one_score < team_two_score ? teams.reverse : team
>     end
>   end
> ```
> 
> And then using `match.winning_team` and `match.defeated_team` in the view?
> 
> Therefore it's more readable in the view what we're actually rendering.
> </details>
> Also, this `"-"` should be handled on the view side, not here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Comment by jotka87** [comment]
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

_[app/models/match.rb, line 18 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRd5_ktJcBzYlmT5Ggl:-KRdKLUTw-cemsWl9zI1:buqto4f) ([raw file](https://github.com/pczarn/gameroom-task/blob/ca81402ca8746e72c88d6d0d78013bd465c8b018/app/models/match.rb#L18)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> Also, this `"-"` should be handled on the view side, not here.
> </details>
> There is a typo in `teams_in_order` in above code snippet, it should be:
> 
> ``` ruby
>   def teams_in_order
>     @teams_in_order ||= begin
>       return teams unless team_one_score && team_two_score
>       team_one_score < team_two_score ? teams.reverse : teams
>     end
>   end
> ```

---

_[app/views/matches/_display_short.html.erb, line 12 at r5](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRdIz-mF4O-yLyOvDi1:-KRdIz-nPNjIpReBr7B7:b-fi5vsm) ([raw file](https://github.com/pczarn/gameroom-task/blob/b58aa24b974c434c0ca081bdc7afbae2f5df6c99/app/views/matches/_display_short.html.erb#L12)):_

> ``` erb
> <%= time_tag match.played_at %>
> 
> <%= link_to "(show)", match %>
> ```

here should go link to edit, so not `match` but `edit_match_path(match)`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Comment by pczarn** [comment]
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

_[app/models/match.rb, line 18 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRd5_ktJcBzYlmT5Ggl:-KRgbg97TfG2vE4mmr7f:bc6qff6) ([raw file](https://github.com/pczarn/gameroom-task/blob/ca81402ca8746e72c88d6d0d78013bd465c8b018/app/models/match.rb#L18)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> There is a typo in `teams_in_order` in above code snippet, it should be:
> 
> ``` ruby
>   def teams_in_order
>     @teams_in_order ||= begin
>       return teams unless team_one_score && team_two_score
>       team_one_score < team_two_score ? teams.reverse : teams
>     end
>   end
> ```
> 
> </details>
> Ok. I added these changes.
> How about sorting. This has a long call to `sort` because I can't use `reverse` which reverses the order even when both scores are nil:
> 
> ``` ruby
>   def teams_in_order
>     @teams_in_order ||= teams.sort {|team_a, team_b| team_b.score <=> team_a.score }
>   end
> ```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Comment by jotka87** [comment]
Reviewed 2 of 2 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Comment by jotka87** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[spec/models/match_spec.rb, line 102 at r7](https://reviewable.io:443/reviews/pczarn/gameroom-task/3#-KRh6z7LY-3n-dWcKTPu:-KRh6z7LY-3n-dWcKTPv:b3ny5bg) ([raw file](https://github.com/pczarn/gameroom-task/blob/89abc378895aa736f6a8011c894a287508b2aedb/spec/models/match_spec.rb#L102)):_

> ``` Ruby
>         expect(match.teams_in_order).to eq(match.teams)
>       end
>     end
> ```

you should also add one test for case when first team has lower score than the second

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Comment by jotka87** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/3)_

**Pull request merged**
