### PR TITLE
Add statistics

### PR DESCRIPTION
**Pull request by pczarn**
This change is [Reviewable](https://reviewable.io/reviews/pczarn/gameroom-task/25)

### CODE REVIEW

**Comment by kapone89** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[app/models/game.rb, line 6 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/25#-KWXkmer-CvdvcPR7okx:-KWXkmer-CvdvcPR7oky:b-f2oj3g) ([raw file](https://github.com/pczarn/gameroom-task/blob/af61322291bd3b62eac5b42bdc545d079982adce/app/models/game.rb#L6)):_

> ``` Ruby
>   has_many :matches
>   has_many :tournaments
>   has_many :game_users
> ```

You should add `dependent: :destroy` to all has_many relations

---

_[app/representers/game_user_representer.rb, line 9 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/25#-KWXlbstpqJH_5OTSPUi:-KWXlbstpqJH_5OTSPUj:b-23qqqz) ([raw file](https://github.com/pczarn/gameroom-task/blob/af61322291bd3b62eac5b42bdc545d079982adce/app/representers/game_user_representer.rb#L9)):_

> ``` Ruby
> 
>   def basic
>     [game_user.user_id, game_user.mean]
> ```

Why not { user_id: ..., mean: ...} ?

---

_[app/representers/games_representer.rb, line 11 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/25#-KWXl3b66Lb67azVGmlv:-KWXl3b66Lb67azVGmlw:b2nhjbj) ([raw file](https://github.com/pczarn/gameroom-task/blob/af61322291bd3b62eac5b42bdc545d079982adce/app/representers/games_representer.rb#L11)):_

> ``` Ruby
> 
>   def with_stats
>     @games.map { |game| GameRepresenter.new(game).with_stats }
> ```

N+1

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/25)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[app/models/game.rb, line 6 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/25#-KWXkmer-CvdvcPR7okx:-KWXqGWezrukqwN614LR:b8b5mln) ([raw file](https://github.com/pczarn/gameroom-task/blob/af61322291bd3b62eac5b42bdc545d079982adce/app/models/game.rb#L6)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> You should add `dependent: :destroy` to all has_many relations
> </details>
> Done. Though I think games were not meant to be destroyed in the frontend, the API currently allows destroying

---

_[app/representers/game_user_representer.rb, line 9 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/25#-KWXlbstpqJH_5OTSPUi:-KWXr41HE2WlCI2IBudK:b-8hg85i) ([raw file](https://github.com/pczarn/gameroom-task/blob/af61322291bd3b62eac5b42bdc545d079982adce/app/representers/game_user_representer.rb#L9)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Why not { user_id: ..., mean: ...} ?
> </details>
> That's better. Ok, changed

---

_[app/representers/games_representer.rb, line 11 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/25#-KWXl3b66Lb67azVGmlv:-KWXqZz0laQKgvUWwkoN:b-886gsx) ([raw file](https://github.com/pczarn/gameroom-task/blob/af61322291bd3b62eac5b42bdc545d079982adce/app/representers/games_representer.rb#L11)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> N+1
> </details>
> Fixed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/25)_

**Comment by kapone89** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[app/representers/games_representer.rb, line 11 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/25#-KWXl3b66Lb67azVGmlv:-KWYBi-gDSoc_4QVKTZb:b-59gnw) ([raw file](https://github.com/pczarn/gameroom-task/blob/af61322291bd3b62eac5b42bdc545d079982adce/app/representers/games_representer.rb#L11)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> Fixed
> </details>
> I'm not sure... Please double-check in console

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/25)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[app/representers/games_representer.rb, line 11 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/25#-KWXl3b66Lb67azVGmlv:-KWYWBkikbBCFFg8irMD:bzeghlx) ([raw file](https://github.com/pczarn/gameroom-task/blob/af61322291bd3b62eac5b42bdc545d079982adce/app/representers/games_representer.rb#L11)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> I'm not sure... Please double-check in console
> </details>
> Right, there's `order` on `game_users` too. Done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/25)_

**Comment by kapone89** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/25)_

**Pull request merged**
