### PR TITLE
Authorization with Pundit

### PR DESCRIPTION
**Pull request by pczarn**
This change is [Reviewable](https://reviewable.io/reviews/pczarn/gameroom-task/16)

### CODE REVIEW

**Comment by mkarbowiak** [comment]
:lgtm:

---

Reviewed 34 of 34 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[app/controllers/matches_controller.rb, line 45 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/16#-KTTTci4fRtMUCNWTYjZ:-KTTTci4fRtMUCNWTYj_:bkjfbfs) ([raw file](https://github.com/pczarn/gameroom-task/blob/795fecb1b7d40cf084855e7d2a737f21a9c94afd/app/controllers/matches_controller.rb#L45)):_

> ``` Ruby
> 
>   def destroy
>     authorize @match
> ```

Can this be DRYed up? Those `authorize` calls?

---

_[app/policies/game_policy.rb, line 1 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/16#-KTTU-qkTH-hqyqPNZBP:-KTTU-qkTH-hqyqPNZBQ:b4qe9lz) ([raw file](https://github.com/pczarn/gameroom-task/blob/795fecb1b7d40cf084855e7d2a737f21a9c94afd/app/policies/game_policy.rb#L1)):_

> ``` Ruby
> class GamePolicy < ApplicationPolicy
> ```

Those policies are Pundit config?

---

_[spec/controllers/tournaments_controller_spec.rb, line 97 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/16#-KTTURLnEgGFx-O9eDNs:-KTTURLoYSGiTE_P86tz:b-4cqbl6) ([raw file](https://github.com/pczarn/gameroom-task/blob/795fecb1b7d40cf084855e7d2a737f21a9c94afd/spec/controllers/tournaments_controller_spec.rb#L97)):_

> ``` Ruby
>       it "fails" do
>         expect { updating }.to raise_error(Pundit::NotAuthorizedError)
>       end
> ```

We know it `"fails"` when it's supposed to raise error. Avoid redundant descriptions where possible.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/16#-:-KTTUkiaIzSfHraqCSOa:bnfp4nl)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[app/controllers/matches_controller.rb, line 45 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/16#-KTTTci4fRtMUCNWTYjZ:-KThYO1a2NSUJ4qAcxM1:b77vcyk) ([raw file](https://github.com/pczarn/gameroom-task/blob/795fecb1b7d40cf084855e7d2a737f21a9c94afd/app/controllers/matches_controller.rb#L45)):_
<details><summary>

<i>Previously, mkarbowiak (Mateusz Karbowiak) wrote…</i></summary>



> Can this be DRYed up? Those `authorize` calls?
> </details>
> Yes. I found out they take the action name from `params[:action]`.
> Done

---

_[app/policies/game_policy.rb, line 1 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/16#-KTTU-qkTH-hqyqPNZBP:-KThYjEEp6llKTEv35W9:b-7axei6) ([raw file](https://github.com/pczarn/gameroom-task/blob/795fecb1b7d40cf084855e7d2a737f21a9c94afd/app/policies/game_policy.rb#L1)):_
<details><summary>

<i>Previously, mkarbowiak (Mateusz Karbowiak) wrote…</i></summary>



> Those policies are Pundit config?
> </details>
> What do you mean by 'config'? They simply implement policies. They are almost POROs.

---

_[spec/controllers/tournaments_controller_spec.rb, line 97 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/16#-KTTURLnEgGFx-O9eDNs:-KThYXLCPZVIgicSW_x-:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/795fecb1b7d40cf084855e7d2a737f21a9c94afd/spec/controllers/tournaments_controller_spec.rb#L97)):_
<details><summary>

<i>Previously, mkarbowiak (Mateusz Karbowiak) wrote…</i></summary>



> We know it `"fails"` when it's supposed to raise error. Avoid redundant descriptions where possible.
> </details>
> Done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/16)_

**Comment by mkarbowiak** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[spec/controllers/tournaments_controller_spec.rb, line 97 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/16#-KTTURLnEgGFx-O9eDNs:-KU13WyEljUXMWBAKn0j:b-umka6i) ([raw file](https://github.com/pczarn/gameroom-task/blob/795fecb1b7d40cf084855e7d2a737f21a9c94afd/spec/controllers/tournaments_controller_spec.rb#L97)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> Done
> </details>
> I meant
> `it { expect { updating }.to raise_error(Pundit::NotAuthorizedError) }`
> reading that line says everything you need to say about this test. No need for description at all.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/16)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[spec/controllers/tournaments_controller_spec.rb, line 97 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/16#-KTTURLnEgGFx-O9eDNs:-KU153CUh571fIun0JOh:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/795fecb1b7d40cf084855e7d2a737f21a9c94afd/spec/controllers/tournaments_controller_spec.rb#L97)):_
<details><summary>

<i>Previously, mkarbowiak (Mateusz Karbowiak) wrote…</i></summary>



> I meant
> `it { expect { updating }.to raise_error(Pundit::NotAuthorizedError) }`
> reading that line says everything you need to say about this test. No need for description at all.
> </details>
> Done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/16)_

**Comment by mkarbowiak** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/16)_

**Pull request merged**
