### PR TITLE
Add rounds logic and views

### PR DESCRIPTION
**Pull request by pczarn**
This change is [Reviewable](https://reviewable.io/reviews/pczarn/gameroom-task/11)

### CODE REVIEW

**Comment by mskv** [comment]
Reviewed 19 of 20 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[app/services/finish_match.rb, line 1 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/11#-KSu5tb9z5R4nUlB2jAG:-KSu5tb9z5R4nUlB2jAH:b1cncs4) ([raw file](https://github.com/pczarn/gameroom-task/blob/43b14f462d705f33d6afed2fdbb40b08b058fec3/app/services/finish_match.rb#L1)):_

> ``` Ruby
> class FinishMatch
> ```

There are multiple problems with this class. Whether we WANT to refactor the code here is a different matter, because we're pressed for time, we're behind the schedule. That's for you to decide if you have time for it. 

As a source and inspiration I recommend for instance watching some Sandi Metz videos on YT, especially about SOLID principles.

The main thing is that these services don't have "single responsibility", like we're also building next match and updating tournament. The logic is also messy, for instance in controller we do `match_params = @match.round.present? ? match_in_tournament_params : friendly_match_params` and here we're making a similar distinction `@round = match.round; @tournament = @round && @round.tournament`. Here we're changing the behaviour of UpdateFinishedMatch by mutating its state with `alert` or `end_tournament` setters. It may be working, but it's very difficult to reason about this code. For instance when I look at `if @end_tournament` in `UpdateFinishedMatch` I need to look at `@update.end_tournament = true` in `FinishMatch` nested in some if. But wait, the whole method is also if-ed with `@tournament.present?` which in turn depends on another line in `@tournament = @round && @round.tournament`. Things like this make code very difficult to read.

I'm not saying it's an easy fix - object oriented design is not easy. But all good practices point towards clear data flow and avoiding mutability. Depending on something that happened in a different object under a bunch of if-s is a code smell and it's very difficult to understand. 

Oh, and I also realize that it's easy to say and more difficult to actually do. 

---

_[app/services/finish_match.rb, line 72 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/11#-KStzlNCDGw6knvSWghg:-KStzlNDwxMyk3jWE1_2:bc0odta) ([raw file](https://github.com/pczarn/gameroom-task/blob/43b14f462d705f33d6afed2fdbb40b08b058fec3/app/services/finish_match.rb#L72)):_

> ``` Ruby
> 
>   def other_match_in_pair
>     @round.matches[index_in_round ^ 1]
> ```

nice trick, I'd have never thought of that.

---

_[app/services/finish_match.rb, line 132 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/11#-KSu0R19Bg4uNZ_IN669:-KSu0R19Bg4uNZ_IN66A:bnsvbnp) ([raw file](https://github.com/pczarn/gameroom-task/blob/43b14f462d705f33d6afed2fdbb40b08b058fec3/app/services/finish_match.rb#L132)):_

> ``` Ruby
>   def send_mails
>     if @next_match
>       UpdateFinishedMatch.delay.notify_about_match_result(@match.id)
> ```

Where does this `delay` come from? This code seems to just work in test due to `allow(described_class).to receive(:delay).and_return(described_class)`. What is the purpose of this?

---

_[app/views/tournament_status_mailer/notify_about_match_result.html.erb, line 3 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/11#-KSttgiUh81gcU89Oq71:-KSttgiUh81gcU89Oq72:bhs6v22) ([raw file](https://github.com/pczarn/gameroom-task/blob/43b14f462d705f33d6afed2fdbb40b08b058fec3/app/views/tournament_status_mailer/notify_about_match_result.html.erb#L3)):_

> ``` erb
> <h1>Hi, <%= @user.name -%>,</h1>
> <p>
>   <% if @result == :win %>
> ```

You don't assign @result anywhere I think.

---

_[spec/mailers/tournament_status_mailer_spec.rb, line 39 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/11#-KStw4KY9RGaLJJzLjTH:-KStw4KZBs9ES4w3KDCs:bv2lwvu) ([raw file](https://github.com/pczarn/gameroom-task/blob/43b14f462d705f33d6afed2fdbb40b08b058fec3/spec/mailers/tournament_status_mailer_spec.rb#L39)):_

> ``` Ruby
>   end
> 
>   describe ".notify_about_match_result" do
> ```

It may also expect to assign "@result" to the body. First mock the situation when someone has won and then

```
it 'includes information about result' do
    expect(mail.body.encoded).to match("You won the match")
end
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/11)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[app/services/finish_match.rb, line 1 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/11#-KSu5tb9z5R4nUlB2jAG:-KSvI2xgNoqhB65mCTXV:b1l64c0) ([raw file](https://github.com/pczarn/gameroom-task/blob/43b14f462d705f33d6afed2fdbb40b08b058fec3/app/services/finish_match.rb#L1)):_
<details><summary>

<i>Previously, mskv (Michał Podwórny) wrote…</i></summary>



> There are multiple problems with this class. Whether we WANT to refactor the code here is a different matter, because we're pressed for time, we're behind the schedule. That's for you to decide if you have time for it. 
> 
> As a source and inspiration I recommend for instance watching some Sandi Metz videos on YT, especially about SOLID principles.
> 
> The main thing is that these services don't have "single responsibility", like we're also building next match and updating tournament. The logic is also messy, for instance in controller we do `match_params = @match.round.present? ? match_in_tournament_params : friendly_match_params` and here we're making a similar distinction `@round = match.round; @tournament = @round && @round.tournament`. Here we're changing the behaviour of UpdateFinishedMatch by mutating its state with `alert` or `end_tournament` setters. It may be working, but it's very difficult to reason about this code. For instance when I look at `if @end_tournament` in `UpdateFinishedMatch` I need to look at `@update.end_tournament = true` in `FinishMatch` nested in some if. But wait, the whole method is also if-ed with `@tournament.present?` which in turn depends on another line in `@tournament = @round && @round.tournament`. Things like this make code very difficult to read.
> 
> I'm not saying it's an easy fix - object oriented design is not easy. But all good practices point towards clear data flow and avoiding mutability. Depending on something that happened in a different object under a bunch of if-s is a code smell and it's very difficult to understand. 
> 
> Oh, and I also realize that it's easy to say and more difficult to actually do. 
> </details>
> I will find enough time for it on Monday.

I remember SOLID principles in name, but don't know them in practice. I didn't write OOP in the last 2-3 years.

Perhaps by creating classes `CreateNextMatch`, `EndTournament`, `SetAlert` etc. I will be able to assign their instance (or two) in place of 'update' and give them separate responsibility. 

---

_[app/services/finish_match.rb, line 132 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/11#-KSu0R19Bg4uNZ_IN669:-KSvAvIDH105pfK7z61s:bfa6zr2) ([raw file](https://github.com/pczarn/gameroom-task/blob/43b14f462d705f33d6afed2fdbb40b08b058fec3/app/services/finish_match.rb#L132)):_
<details><summary>

<i>Previously, mskv (Michał Podwórny) wrote…</i></summary>



> Where does this `delay` come from? This code seems to just work in test due to `allow(described_class).to receive(:delay).and_return(described_class)`. What is the purpose of this?
> </details>
> The `delay` comes from sidekiq so that delivery of mails is delayed so that it doesn't block the controller in case the delivery takes time to finish. I pass `@match.id` and not `@match` for that reason, too.

---

_[app/views/tournament_status_mailer/notify_about_match_result.html.erb, line 3 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/11#-KSttgiUh81gcU89Oq71:-KSvFrbeoI7JwZrLzhmL:b-qssebl) ([raw file](https://github.com/pczarn/gameroom-task/blob/43b14f462d705f33d6afed2fdbb40b08b058fec3/app/views/tournament_status_mailer/notify_about_match_result.html.erb#L3)):_
<details><summary>

<i>Previously, mskv (Michał Podwórny) wrote…</i></summary>



> You don't assign @result anywhere I think.
> </details>
> fixed.

---

_[spec/mailers/tournament_status_mailer_spec.rb, line 39 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/11#-KStw4KY9RGaLJJzLjTH:-KSvD5V8JG8HhqKImiuo:b-qbvrzs) ([raw file](https://github.com/pczarn/gameroom-task/blob/43b14f462d705f33d6afed2fdbb40b08b058fec3/spec/mailers/tournament_status_mailer_spec.rb#L39)):_
<details><summary>

<i>Previously, mskv (Michał Podwórny) wrote…</i></summary>



> It may also expect to assign "@result" to the body. First mock the situation when someone has won and then
> 
> ```
> it 'includes information about result' do
>     expect(mail.body.encoded).to match("You won the match")
> end
> ```
> 
> </details>
> Done.

the `match` in `.to match` in rspec is replaced by `let(:match)`, haha.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/11)_

**Comment by mskv** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[app/services/finish_match.rb, line 132 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/11#-KSu0R19Bg4uNZ_IN669:-KSvTAHhL1DjU2yHQTcj:b-kftcdh) ([raw file](https://github.com/pczarn/gameroom-task/blob/43b14f462d705f33d6afed2fdbb40b08b058fec3/app/services/finish_match.rb#L132)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> The `delay` comes from sidekiq so that delivery of mails is delayed so that it doesn't block the controller in case the delivery takes time to finish. I pass `@match.id` and not `@match` for that reason, too.
> </details>
> Oh, you're right. I've only used Sidekiq workers, I had no idea that Sidekiq monkey-patches all classes with a `delay` method. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/11)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[app/services/finish_match.rb, line 1 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/11#-KSu5tb9z5R4nUlB2jAG:-KT96K9jfIIpCz34-tpk:b-8cz74w) ([raw file](https://github.com/pczarn/gameroom-task/blob/43b14f462d705f33d6afed2fdbb40b08b058fec3/app/services/finish_match.rb#L1)):_
done.

> The logic is also messy, for instance in controller we do match_params = @match.round.present? ? match_in_tournament_params : friendly_match_params

I'm not sure this should change, I think getting params is the reponsibility of the controller

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/11)_

**Comment by mskv** [comment]
Review status: 16 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

_[app/services/finish_match.rb, line 1 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/11#-KSu5tb9z5R4nUlB2jAG:-KT9vgSFXliMQL9yc0He:b-r3snyk) ([raw file](https://github.com/pczarn/gameroom-task/blob/43b14f462d705f33d6afed2fdbb40b08b058fec3/app/services/finish_match.rb#L1)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> done.
> 
> > The logic is also messy, for instance in controller we do match_params = @match.round.present? ? match_in_tournament_params : friendly_match_params
> 
> I'm not sure this should change, I think getting params is the reponsibility of the controller
> </details>
> Those services sound good. In my opinion it's the easies when service objects just get a message, do something, return value - and that's all. They don't have any state and their behaviour depends only on the input - it cannot be changed multiple times using setter methods like below.

As to the `match_params = @match.round.present? ? match_in_tournament_params : friendly_match_params` and `@tournament = @round && @round.tournament` - it's definitely repeated logic. In both cases we discern whether a match is a tournament match or friendly match. But let's leave this for now and we can divide the logic into services first, then think about this thing.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/11)_

**Comment by mkarbowiak** [comment]
Reviewed 1 of 20 files at r1, 1 of 2 files at r4, 3 of 5 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/11)_

**Comment by mkarbowiak** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/11#-:-KTEKze7nf-93NIMyMFT:bnfp4nl)_

**Pull request merged**
