### PR TITLE
Add editing tournaments

### PR DESCRIPTION
**Pull request by pczarn**
This change is [Reviewable](https://reviewable.io/reviews/pczarn/gameroom-task/9)

### CODE REVIEW

**Comment by monttda** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

_[app/controllers/tournaments_controller.rb, line 31 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/9#-KSa49VqyjlbuVdOaNuO:-KSa49VqyjlbuVdOaNuP:b-vtnvba) ([raw file](https://github.com/pczarn/gameroom-task/blob/966e65e3bb75226b7909f10fa04f4cfcba8eae13/app/controllers/tournaments_controller.rb#L31)):_

> ``` Ruby
>       redirect_to edit_tournament_path(@tournament)
>     else
>       if @tournament.open?
> ```

how do you change the status of the tournament ? 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/9)_

**Comment by pczarn** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

_[app/controllers/tournaments_controller.rb, line 31 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/9#-KSa49VqyjlbuVdOaNuO:-KSaGVJ-kVA4bxE6UEDX:b-4qgkp2) ([raw file](https://github.com/pczarn/gameroom-task/blob/966e65e3bb75226b7909f10fa04f4cfcba8eae13/app/controllers/tournaments_controller.rb#L31)):_
<details><summary>

<i>Previously, monttda (Daniel Montenegro) wrote…</i></summary>



> how do you change the status of the tournament ? 
> </details>
> I change it in a worker that is added in another PR.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/9)_

**Comment by mskv** [comment]
Reviewed 1 of 5 files at r1, 1 of 23 files at r2, 14 of 24 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[app/controllers/tournaments_controller.rb, line 39 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/9#-KSlDGFsiOzy0aSwBk9r:-KSlDGFsiOzy0aSwBk9s:banc1ah) ([raw file](https://github.com/pczarn/gameroom-task/blob/72d50b2ec4ef919da874964ae43c241055f0baa1/app/controllers/tournaments_controller.rb#L39)):_

> ``` Ruby
>   end
> 
>   def add_team
> ```

Please take a look at:

http://jeromedalbert.com/how-dhh-organizes-his-rails-controllers/

It's a convention of keeping the controller actions CRUD. And - if needed - defining additional abstract controllers based on business logic.

Here for instance we could define a controller like `TeamTournamentMembershipController`. 

And we'd have `#create` and `#destroy` actions for adding and removing teams from tournaments. 

If you don't want, don't do it, it's just a pattern.

---

_[app/models/tournament.rb, line 32 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/9#-KSlGSnIuMPKxO8E6xqz:-KSlGSnJOKxfn_PZcxjt:bry2tbl) ([raw file](https://github.com/pczarn/gameroom-task/blob/72d50b2ec4ef919da874964ae43c241055f0baa1/app/models/tournament.rb#L32)):_

> ``` Ruby
>   end
> 
>   def potential_members
> ```

I don't mind all this logic here, but just to let you know: in huge projects putting business logic in models ends badly. Every business-logic-related stuff should be explicit and well-encapsulated, and models should only be used for persistence and (maybe) validations.

Take a look at those examples of good practices:
http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/

You don't need to change anything here, but just keep in mind that ideally this would not be here. Same with `full?` `overfull?` etc. from above.

---

_[app/views/tournaments/_display.html.erb, line 8 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/9#-KSlG9cTf029fq8m1gTY:-KSlG9cTf029fq8m1gTZ:b-b0e4yh) ([raw file](https://github.com/pczarn/gameroom-task/blob/72d50b2ec4ef919da874964ae43c241055f0baa1/app/views/tournaments/_display.html.erb#L8)):_

> ``` erb
>   <%= render partial: "teams/display_long", locals: { team: team_tournament.team } %>
> 
>   <% if @tournament.open? && @tournament.owned_by?(current_user) %>
> ```

you passed @tournament in locals as tournament. I don't know how Rails templates work, but I assume you should be using tournament here for consistence.

---

_[app/views/tournaments/_display_edit.html.erb, line 4 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/9#-KSlFp7o1-3UugZghMjq:-KSlFp7p9i6lNQLs_tj3:b-b0e4yh) ([raw file](https://github.com/pczarn/gameroom-task/blob/72d50b2ec4ef919da874964ae43c241055f0baa1/app/views/tournaments/_display_edit.html.erb#L4)):_

> ``` erb
>   <h3>Add a team with members</h3>
>   <%= form_for @team, url: tournament_add_team_path(tournament), method: :post do |f| %>
>     <%= render partial: "teams/form", locals: { f: f, potential_members: @tournament.potential_members } %>
> ```

you passed @tournament in locals as tournament. I don't know how Rails templates work, but I assume you should be using tournament here for consistence.

---

_[spec/support/controller_helpers.rb, line 14 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/9#-KSl9rECevyJzqnfOXwV:-KSl9rEDjIQ9WeQrV2nG:b4zj5rc) ([raw file](https://github.com/pczarn/gameroom-task/blob/72d50b2ec4ef919da874964ae43c241055f0baa1/spec/support/controller_helpers.rb#L14)):_

> ``` Ruby
>   end
> 
>   def current_user
> ```

I don't like this. The way it should be handled in test:

```
let(:owner) { build(:user) }
before(:each) { sign_in(owner) }
```

now you could expect `owner` to be the user signed in in your code.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/9)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[app/controllers/tournaments_controller.rb, line 39 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/9#-KSlDGFsiOzy0aSwBk9r:-KSlQlcC6q6qP9cvUteT:btovsxa) ([raw file](https://github.com/pczarn/gameroom-task/blob/72d50b2ec4ef919da874964ae43c241055f0baa1/app/controllers/tournaments_controller.rb#L39)):_
<details><summary>

<i>Previously, mskv (Michał Podwórny) wrote…</i></summary>



> Please take a look at:
> 
> http://jeromedalbert.com/how-dhh-organizes-his-rails-controllers/
> 
> It's a convention of keeping the controller actions CRUD. And - if needed - defining additional abstract controllers based on business logic.
> 
> Here for instance we could define a controller like `TeamTournamentMembershipController`. 
> 
> And we'd have `#create` and `#destroy` actions for adding and removing teams from tournaments. 
> 
> If you don't want, don't do it, it's just a pattern.
> </details>
> I see, I will think about doing it later. Soon I'll need to add more fixes to various models and controllers.

---

_[app/models/tournament.rb, line 32 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/9#-KSlGSnIuMPKxO8E6xqz:-KSlSCM4I88RqbmcTaES:b-ivd3ki) ([raw file](https://github.com/pczarn/gameroom-task/blob/72d50b2ec4ef919da874964ae43c241055f0baa1/app/models/tournament.rb#L32)):_
<details><summary>

<i>Previously, mskv (Michał Podwórny) wrote…</i></summary>



> I don't mind all this logic here, but just to let you know: in huge projects putting business logic in models ends badly. Every business-logic-related stuff should be explicit and well-encapsulated, and models should only be used for persistence and (maybe) validations.
> 
> Take a look at those examples of good practices:
> http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/
> 
> You don't need to change anything here, but just keep in mind that ideally this would not be here. Same with `full?` `overfull?` etc. from above.
> </details>
> I'm not sure which patterns I can use here, but I'll go back to that article later.

---

_[app/views/tournaments/_display.html.erb, line 8 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/9#-KSlG9cTf029fq8m1gTY:-KSlSmf3qCQNxuMrnxmF:b-bhqwsb) ([raw file](https://github.com/pczarn/gameroom-task/blob/72d50b2ec4ef919da874964ae43c241055f0baa1/app/views/tournaments/_display.html.erb#L8)):_
<details><summary>

<i>Previously, mskv (Michał Podwórny) wrote…</i></summary>



> you passed @tournament in locals as tournament. I don't know how Rails templates work, but I assume you should be using tournament here for consistence.
> </details>
> That's a mistake. I didn't know it's possible.

---

_[spec/support/controller_helpers.rb, line 14 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/9#-KSl9rECevyJzqnfOXwV:-KSlTSxaymTEASLisjoR:b8xnxp) ([raw file](https://github.com/pczarn/gameroom-task/blob/72d50b2ec4ef919da874964ae43c241055f0baa1/spec/support/controller_helpers.rb#L14)):_
<details><summary>

<i>Previously, mskv (Michał Podwórny) wrote…</i></summary>



> I don't like this. The way it should be handled in test:
> 
> ```
> let(:owner) { build(:user) }
> before(:each) { sign_in(owner) }
> ```
> 
> now you could expect `owner` to be the user signed in in your code.
> </details>
> Ok. However, `:owner` looks like an owner of tournaments for all tests. Maybe `:current_user`?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/9)_

**Comment by mskv** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[spec/support/controller_helpers.rb, line 14 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/9#-KSl9rECevyJzqnfOXwV:-KSlhhzwJA8MyXiIoRA0:bvk1196) ([raw file](https://github.com/pczarn/gameroom-task/blob/72d50b2ec4ef919da874964ae43c241055f0baa1/spec/support/controller_helpers.rb#L14)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> Ok. However, `:owner` looks like an owner of tournaments for all tests. Maybe `:current_user`?
> </details>
> Sure! With that helper method you can sign_in whoever you want depending on the test. And you can overwrite the logged in user for particular context also if you want.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/9)_

**Comment by pczarn** [comment]
Review status: 12 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

_[app/views/tournaments/_display_edit.html.erb, line 4 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/9#-KSlFp7o1-3UugZghMjq:-KSoh0mLaa0P4_O0lvxI:b-7rl0jd) ([raw file](https://github.com/pczarn/gameroom-task/blob/72d50b2ec4ef919da874964ae43c241055f0baa1/app/views/tournaments/_display_edit.html.erb#L4)):_
<details><summary>

<i>Previously, mskv (Michał Podwórny) wrote…</i></summary>



> you passed @tournament in locals as tournament. I don't know how Rails templates work, but I assume you should be using tournament here for consistence.
> </details>
> done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/9)_

**Comment by mskv** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/9)_

**Pull request merged**
