### PR TITLE
Create tournaments controller

### PR DESCRIPTION
**Pull request by pczarn**
This change is [Reviewable](https://reviewable.io/reviews/pczarn/gameroom-task/6)

### CODE REVIEW

**Comment by wmaciejak** [comment]
Reviewed 11 of 15 files at r1.
Review status: 11 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

_[app/controllers/tournaments_controller.rb, line 5 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/6#-KS6nVttQkIAB7MwxBUL:-KS6nVtuzu6bsnv7Pyw7:bqazqo) ([raw file](https://github.com/pczarn/gameroom-task/blob/84b7ff5485d1139da0c74820b8e0ba62f94612cc/app/controllers/tournaments_controller.rb#L5)):_

> ``` Ruby
> 
>   def index
>     @tournament = Tournament.new(started_at: Time.zone.now)
> ```

Index action should create new  instance of Tournament, are you sure?

---

_[app/helpers/tournaments_helper.rb, line 1 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/6#-KS6oHVnR_6T5pT9LKqR:-KS6oHVnR_6T5pT9LKqS:bjrn3te) ([raw file](https://github.com/pczarn/gameroom-task/blob/84b7ff5485d1139da0c74820b8e0ba62f94612cc/app/helpers/tournaments_helper.rb#L1)):_

> ``` Ruby
> module TournamentsHelper
> ```

We really need empty helper? ;)

---

_[config/routes.rb, line 11 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/6#-KS6oi913MlysxZS2AbT:-KS6oi913MlysxZS2AbU:bekte9e) ([raw file](https://github.com/pczarn/gameroom-task/blob/84b7ff5485d1139da0c74820b8e0ba62f94612cc/config/routes.rb#L11)):_

> ``` Ruby
>   delete "log_out", to: "sessions#destroy", as: "log_out"
> 
>   resources :matches, except: [:show]
> ```

If  you have only one action in `except:` or `only:`, I think you can put it without brackets :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/6)_

**Comment by pczarn** [comment]
Review status: 11 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

_[app/controllers/tournaments_controller.rb, line 5 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/6#-KS6nVttQkIAB7MwxBUL:-KSAnwLVkuGAp18j9m0p:bcq1a1g) ([raw file](https://github.com/pczarn/gameroom-task/blob/84b7ff5485d1139da0c74820b8e0ba62f94612cc/app/controllers/tournaments_controller.rb#L5)):_
<details><summary>

<i>Previously, wojtekmaciej (Wojciech Maciejak) wrote…</i></summary>



> Index action should create new  instance of Tournament, are you sure?
> </details>
> The index action includes creating a new tournament, which is typically in the `new` action, but I have both in one action.

---

_[app/helpers/tournaments_helper.rb, line 1 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/6#-KS6oHVnR_6T5pT9LKqR:-KSAnusoQNkCfDjuD3zK:b-cbix8) ([raw file](https://github.com/pczarn/gameroom-task/blob/84b7ff5485d1139da0c74820b8e0ba62f94612cc/app/helpers/tournaments_helper.rb#L1)):_
<details><summary>

<i>Previously, wojtekmaciej (Wojciech Maciejak) wrote…</i></summary>



> We really need empty helper? ;)
> </details>
> nope :)

---

_[config/routes.rb, line 11 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/6#-KS6oi913MlysxZS2AbT:-KSAoA3lb_VSbH7Na61k:b-l4jprd) ([raw file](https://github.com/pczarn/gameroom-task/blob/84b7ff5485d1139da0c74820b8e0ba62f94612cc/config/routes.rb#L11)):_
<details><summary>

<i>Previously, wojtekmaciej (Wojciech Maciejak) wrote…</i></summary>



> If  you have only one action in `except:` or `only:`, I think you can put it without brackets :)
> </details>
> right.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/6)_

**Comment by wmaciejak** [comment]
Reviewed 1 of 15 files at r1, 2 of 2 files at r2.
Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/6)_

**Comment by wmaciejak** [comment]
Reviewed 1 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/6)_

**Pull request merged**
