### PR TITLE
Add user authentication

### PR DESCRIPTION
**Pull request by pczarn**
This change is [Reviewable](https://reviewable.io/reviews/pczarn/gameroom-task/4)

### CODE REVIEW

**Comment by jotka87** [comment]
Reviewed 28 of 45 files at r1.
Review status: 28 of 33 files reviewed at latest revision, 11 unresolved discussions.

---

_[Gemfile, line 64 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRheu8YL2RtpnoIzXLF:-KRheu8Zadk6Y1_J9iXf:b-171bvy) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/Gemfile#L64)):_

> ``` Ruby
> 
> # Authentication
> gem "argon2"
> ```

each gem should have version specified

---

_[app/controllers/users_controller.rb, line 9 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhA-UE4S931zz0n5sd:-KRhA-UE4S931zz0n5se:bl90dix) ([raw file](https://github.com/pczarn/gameroom-task/blob/d112a699e41e66b19f30921aded732d95c46e960/app/controllers/users_controller.rb#L9)):_

> ``` Ruby
>     @user = User.create(user_params)
>     if @user.save
>       redirect_to root_url, notice: "Signed up."
> ```

`root_path`

---

_[app/helpers/sessions_helper.rb, line 1 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhAJMFXKavicY4vv1M:-KRhAJMGxDwks6fgePoL:b-6j83q5) ([raw file](https://github.com/pczarn/gameroom-task/blob/d112a699e41e66b19f30921aded732d95c46e960/app/helpers/sessions_helper.rb#L1)):_

> ``` Ruby
> module SessionsHelper
> ```

will it be used? About the auto generated files by rails generators - we should keep only those that we will for sure use, the rest should be removed. It can be always added manually. In that case we can prevent our repo to get messy.

---

_[app/helpers/users_helper.rb, line 1 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhArfWCc4xYOCbPSUj:-KRhArfWCc4xYOCbPSUk:b-2guby3) ([raw file](https://github.com/pczarn/gameroom-task/blob/d112a699e41e66b19f30921aded732d95c46e960/app/helpers/users_helper.rb#L1)):_

> ``` Ruby
> module UsersHelper
> ```

same here

---

_[app/models/user.rb, line 23 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhcRrLSrO4x1G9DPYK:-KRhcRrMd4ElRoaGIQ7w:bejzbwj) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/app/models/user.rb#L23)):_

> ``` Ruby
> 
>   def admin?
>     role == 1
> ```

please add `enum` for possible roles user can have

---

_[app/views/users/new.html.erb, line 12 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRheLkhYcvao3EnCpK7:-KRheLkjrb4UUPpiVnQI:b-tcdggb) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/app/views/users/new.html.erb#L12)):_

> ``` erb
>       </ul>
>     </div>
>   <% end %>
> ```

the whole block with errors should go to a partial, it can be rendered by different forms 

---

_[spec/controllers/users_controller_spec.rb, line 18 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhbur29O-4ieX1ebNC:-KRhbur29O-4ieX1ebND:b-mmzw1g) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/spec/controllers/users_controller_spec.rb#L18)):_

> ``` Ruby
>       password: user.password,
>       password_confirmation: user.password,
>     }
> ```

you can use factory girl's method for that - `attributes_for(:user)`

---

_[spec/helpers/sessions_helper_spec.rb, line 1 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhb_PZWxD9guY-ICmY:-KRhb_PZWxD9guY-ICmZ:b-qpr8hx) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/spec/helpers/sessions_helper_spec.rb#L1)):_

> ``` Ruby
> require 'rails_helper'
> ```

similar comment as for helpers

---

_[spec/helpers/users_helper_spec.rb, line 1 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhbcWPNmJLGW7Lbk9e:-KRhbcWPNmJLGW7Lbk9f:b-qpr8hx) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/spec/helpers/users_helper_spec.rb#L1)):_

> ``` Ruby
> require 'rails_helper'
> ```

similar comment as for helpers

---

_[spec/views/sessions/new.html.erb_spec.rb, line 1 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhbEzH2tsRu5XXyiYb:-KRhbEzH2tsRu5XXyiYc:b-q7g3vz) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/spec/views/sessions/new.html.erb_spec.rb#L1)):_

> ``` Ruby
> require 'rails_helper'
> ```

please remove view tests

---

_[spec/views/users/new.html.erb_spec.rb, line 1 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhbACqpHuI_Skrtq2Q:-KRhbACqpHuI_Skrtq2R:b995vu9) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/spec/views/users/new.html.erb_spec.rb#L1)):_

> ``` Ruby
> require 'rails_helper'
> ```

Please remove view tests

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by pczarn** [comment]
Review status: 17 of 28 files reviewed at latest revision, 9 unresolved discussions.

---

_[app/models/user.rb, line 23 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhcRrLSrO4x1G9DPYK:-KRhuSPUAVirsruSPoVs:bb7f2mf) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/app/models/user.rb#L23)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> please add `enum` for possible roles user can have
> </details>
> done

---

_[app/views/users/new.html.erb, line 12 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRheLkhYcvao3EnCpK7:-KRhscvEmKzOzrZrJXMS:b2ni9bh) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/app/views/users/new.html.erb#L12)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> the whole block with errors should go to a partial, it can be rendered by different forms 
> </details>
> ok.

---

_[spec/controllers/users_controller_spec.rb, line 18 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhbur29O-4ieX1ebNC:-KRhpcI3g9PqLW0JXX03:b-boqzi5) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/spec/controllers/users_controller_spec.rb#L18)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> you can use factory girl's method for that - `attributes_for(:user)`
> </details>
> ok. It still doesn't give `password_confirmation` though.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by jotka87** [comment]
Reviewed 1 of 45 files at r1, 10 of 12 files at r3.
Review status: 22 of 28 files reviewed at latest revision, 4 unresolved discussions.

---

_[config/routes.rb, line 3 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhk9g-njZ5hux2SnHl:-KRhk9g0xlittZe99kw3:b-fpldzl) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/config/routes.rb#L3)):_

> ``` Ruby
> Rails.application.routes.draw do
>   get 'log_in' => 'sessions#new', as: 'log_in'
>   post 'log_out' => 'sessions#destroy', as: 'log_out'
> ```

should be `delete 'log_out'`

---

_[config/routes.rb, line 9 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhkNt3ZD-sSBGWZS2V:-KRhkNt48z9nahltWiJm:b1azbpf) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/config/routes.rb#L9)):_

> ``` Ruby
> 
>   resources :users
>   resources :sessions
> ```

should be only for `:new`, `:create` and `:destroy`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by jotka87** [comment]
Reviewed 1 of 12 files at r3.
Review status: 23 of 28 files reviewed at latest revision, 4 unresolved discussions.

---

_[spec/controllers/users_controller_spec.rb, line 18 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhbur29O-4ieX1ebNC:-KRhvyH5W5NnEwwDEUdl:b-snaisw) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/spec/controllers/users_controller_spec.rb#L18)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> ok. It still doesn't give `password_confirmation` though.
> </details>
> add something like this to user factory:
> 
> ``` ruby
> password "password"
> password_confirmation "password" 
> ```
> 
> You don't need to hash password given in params because it's done while saving the record.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by pczarn** [comment]
Review status: 23 of 28 files reviewed at latest revision, 4 unresolved discussions.

---

_[config/routes.rb, line 3 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhk9g-njZ5hux2SnHl:-KRhwDfkDqy-uRN5o0UP:b32wtd) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/config/routes.rb#L3)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> should be `delete 'log_out'`
> </details>
> ok

---

_[config/routes.rb, line 9 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhkNt3ZD-sSBGWZS2V:-KRhx42efDSPFvLvyL1H:bmxwdpg) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/config/routes.rb#L9)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> should be only for `:new`, `:create` and `:destroy`
> </details>
> Should it be only for actions that are used? If so, I only need `[:create]` for forms. `new_session_path` is not used.
> Should it be singular `resource`?
> What about `users` resources?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by jotka87** [comment]
Reviewed 1 of 12 files at r3.
Review status: 20 of 28 files reviewed at latest revision, 4 unresolved discussions.

---

_[app/models/user.rb, line 23 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhcRrLSrO4x1G9DPYK:-KRhycTLD4NOKxjLdLVj:b5pliu1) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/app/models/user.rb#L23)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> done
> </details>
> It's better to have hash enum, like this:
> 
> ``` ruby
> enum role: {
>   user: 0,
>   admin: 1,
> }
> ```
> 
> Therefore we can access the role by key, but store value in the db.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by jotka87** [comment]
Reviewed 3 of 45 files at r1, 1 of 1 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[app/models/user.rb, line 17 at r5](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRi-Shj6SUivUx9IwhU:-KRi-ShkGrJgX-S9EsLi:bapyg7a) ([raw file](https://github.com/pczarn/gameroom-task/blob/5818423c4b3119c412459422a2c5444b523266cc/app/models/user.rb#L17)):_

> ``` Ruby
>   def self.authenticate(email, password)
>     user = User.find_by(email: email)
>     user && Argon2::Password.verify_password(password, user.password_hashed) && user
> ```

unnecessary `user` at the end of the condition.

---

_[config/routes.rb, line 9 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhkNt3ZD-sSBGWZS2V:-KRi2cTxjDLDRBZEggRc:b-yj0k0d) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/config/routes.rb#L9)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> Should it be only for actions that are used? If so, I only need `[:create]` for forms. `new_session_path` is not used.
> Should it be singular `resource`?
> What about `users` resources?
> </details>
> sessions and users are ok for now but in the nearest future we would need the rest of the actions for user to be able to manage and display user account.

About the plural/singular form
- for users, I guess we should stick with plural because we should be able as a user to display other users in the app, you can check what exact routes are being generated for singular and plural forms by running the command: `bundle exec rake routes`. 
- for sessions it could be in fact singular form.

One last note: keep routes grouped so it will be simpler to find them, for example:

``` ruby
root "sessions#new"
 
resources :users, only: [:create]
get sign_up: "users#new", as: :sign_up

resources :sessions, only: [:create]
get    log_in:  "sessions#new",     as: :log_in
delete log_out: "sessions#destroy", as: :log_out
```

I guess it's a little bit cleaner

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by jotka87** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by pczarn** [comment]
Review status: 27 of 28 files reviewed at latest revision, 2 unresolved discussions.

---

_[app/models/user.rb, line 17 at r5](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRi-Shj6SUivUx9IwhU:-KRiBkpbI3VHI6Sy71XJ:bb50y38) ([raw file](https://github.com/pczarn/gameroom-task/blob/5818423c4b3119c412459422a2c5444b523266cc/app/models/user.rb#L17)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> unnecessary `user` at the end of the condition.
> </details>
> It needs to return the user somehow

---

_[config/routes.rb, line 9 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRhkNt3ZD-sSBGWZS2V:-KRiCD-rM-Ewi_J1uzW8:b-ye0vyo) ([raw file](https://github.com/pczarn/gameroom-task/blob/6a39aabf923e3468ffb93aa743f45ff49711789f/config/routes.rb#L9)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> sessions and users are ok for now but in the nearest future we would need the rest of the actions for user to be able to manage and display user account.
> 
> About the plural/singular form
> - for users, I guess we should stick with plural because we should be able as a user to display other users in the app, you can check what exact routes are being generated for singular and plural forms by running the command: `bundle exec rake routes`. 
> - for sessions it could be in fact singular form.
> 
> One last note: keep routes grouped so it will be simpler to find them, for example:
> 
> ``` ruby
> root "sessions#new"
>  
> resources :users, only: [:create]
> get sign_up: "users#new", as: :sign_up
> 
> resources :sessions, only: [:create]
> get    log_in:  "sessions#new",     as: :log_in
> delete log_out: "sessions#destroy", as: :log_out
> ```
> 
> I guess it's a little bit cleaner
> </details>
> Yes, it's cleaner. I think admins will need to manage users, so of course it should be a plural resource.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by jotka87** [comment]
Review status: 27 of 28 files reviewed at latest revision, 2 unresolved discussions.

---

_[config/routes.rb, line 9 at r7](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRiFF8Z5LeIRKQeAtpE:-KRiFF8Z5LeIRKQeAtpF:bna0saz) ([raw file](https://github.com/pczarn/gameroom-task/blob/545a99c1b1c123f10568bf76b577168b39b9542a/config/routes.rb#L9)):_

> ``` Ruby
>   resource :sessions, only: [:create]
>   get "log_in" => "sessions#new", as: "log_in"
>   delete "log_out" => "sessions#destroy", as: "log_out"
> ```

use newer hash convention: `key: "value"`, and you can also pass symbol for the route name, so:

``` ruby
delete log_out: "sessions#destroy", as: :log_out
```

It's more readable.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by jotka87** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[config/routes.rb, line 9 at r7](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRiFF8Z5LeIRKQeAtpE:-KRiGriQUfl9UuJ6a4Jp:b7rur40) ([raw file](https://github.com/pczarn/gameroom-task/blob/545a99c1b1c123f10568bf76b577168b39b9542a/config/routes.rb#L9)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> use newer hash convention: `key: "value"`, and you can also pass symbol for the route name, so:
> 
> ``` ruby
> delete log_out: "sessions#destroy", as: :log_out
> ```
> 
> It's more readable.
> </details>
> That passes everything in one hash argument to `delete`, which doesn't work, so I'll write `delete { log_out: "sessions#destroy" }, as: :log_out`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by jotka87** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[app/models/user.rb, line 17 at r5](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRi-Shj6SUivUx9IwhU:-KRiHry2HfH4thn_2VES:b-rvhhfk) ([raw file](https://github.com/pczarn/gameroom-task/blob/5818423c4b3119c412459422a2c5444b523266cc/app/models/user.rb#L17)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> It needs to return the user somehow
> </details>
> so maybe this way?
> 
> ``` ruby
> return unless user = User.find_by(email: email)
> Argon2::Password.verify_password(password, user.password_hashed) && user
> ```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by jotka87** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[app/controllers/application_controller.rb, line 10 at r8](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRloPpTPMoTn4eEYTAs:-KRloPpTPMoTn4eEYTAt:ba6702y) ([raw file](https://github.com/pczarn/gameroom-task/blob/e138a44fe9637243d41bb5a6e610c819abab217d/app/controllers/application_controller.rb#L10)):_

> ``` Ruby
>   def authenticate!
>     unless session[:user_id]
>       redirect_to root_path
> ```

change this to `log_in_path`, and basically it could be a one-liner

---

_[app/controllers/sessions_controller.rb, line 1 at r8](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRlp2NE_P1NmOrzeMWT:-KRlp2NFMFAdmsrrbmrU:b-8wwx0n) ([raw file](https://github.com/pczarn/gameroom-task/blob/e138a44fe9637243d41bb5a6e610c819abab217d/app/controllers/sessions_controller.rb#L1)):_

> ``` Ruby
> class SessionsController < ApplicationController
> ```

logged in user shouldn't be able to visit login page and registration page

---

_[config/routes.rb, line 2 at r8](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRlo9wPl0Hv4DJ3KgqA:-KRlo9wPl0Hv4DJ3KgqB:b-clvsno) ([raw file](https://github.com/pczarn/gameroom-task/blob/e138a44fe9637243d41bb5a6e610c819abab217d/config/routes.rb#L2)):_

> ``` Ruby
> Rails.application.routes.draw do
>   root "sessions#new"
> ```

change root to `"matches#index"`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[app/controllers/application_controller.rb, line 10 at r8](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRloPpTPMoTn4eEYTAs:-KRlzqEL65SnrnaDJYGF:bb7f2mf) ([raw file](https://github.com/pczarn/gameroom-task/blob/e138a44fe9637243d41bb5a6e610c819abab217d/app/controllers/application_controller.rb#L10)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> change this to `log_in_path`, and basically it could be a one-liner
> </details>
> done

---

_[app/controllers/sessions_controller.rb, line 1 at r8](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRlp2NE_P1NmOrzeMWT:-KRlzrAqjR49IHOsSXMM:biy2esc) ([raw file](https://github.com/pczarn/gameroom-task/blob/e138a44fe9637243d41bb5a6e610c819abab217d/app/controllers/sessions_controller.rb#L1)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> logged in user shouldn't be able to visit login page and registration page
> </details>
> both done

---

_[config/routes.rb, line 2 at r8](https://reviewable.io:443/reviews/pczarn/gameroom-task/4#-KRlo9wPl0Hv4DJ3KgqA:-KRlzpL1ApS_ExL6Lp-E:bb7f2mf) ([raw file](https://github.com/pczarn/gameroom-task/blob/e138a44fe9637243d41bb5a6e610c819abab217d/config/routes.rb#L2)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> change root to `"matches#index"`
> </details>
> done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Comment by jotka87** [comment]
Reviewed 5 of 5 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/4)_

**Pull request merged**
