### PR TITLE
Improve code and app quality

### PR DESCRIPTION
**Pull request by pczarn**
This change is [Reviewable](https://reviewable.io/reviews/pczarn/gameroom-task/17)

### CODE REVIEW

**Comment by kapone89** [comment]
Reviewed 18 of 39 files at r1.
Review status: 18 of 39 files reviewed at latest revision, 3 unresolved discussions.

---

_[app/models/user.rb, line 28 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUMUHQsZi6xwIO7qwef:-KUMUHQsZi6xwIO7qweg:b-d8bskk) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/app/models/user.rb#L28)):_

> ``` Ruby
> 
>   validates :name, :email, presence: true, uniqueness: true
>   validates :email, format: /@/
> ```

Please improve this regexp.

---

_[app/views/tournament_status_mailer/notify_about_match_result.text.erb, line 5 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUMVLlQXEVOFA_fv9an:-KUMVLlQXEVOFA_fv9ao:bvx4ylj) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/app/views/tournament_status_mailer/notify_about_match_result.text.erb#L5)):_

> ``` erb
> 
> <% if @result == :win %>
>   You won the match.
> ```

I guess you will have 2 blank spaces at the beginning of line.

---

_[app/views/tournament_status_mailer/notify_about_match_result.text.erb, line 10 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUMUygGseBYJExclE2J:-KUMUygGseBYJExclE2K:b-4hw43a) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/app/views/tournament_status_mailer/notify_about_match_result.text.erb#L10)):_

> ``` erb
> <% else %>
>   The match is finished.
> <% end %>
> ```

There should be more information (what match, etc.). And please use "case" here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/17)_

**Comment by kapone89** [comment]
Reviewed 1 of 39 files at r1.
Review status: 19 of 39 files reviewed at latest revision, 4 unresolved discussions.

---

_[config/routes.rb, line 18 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUMWlO4yKBSRP40qMxg:-KUMWlO4yKBSRP40qMxh:boyexco) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/config/routes.rb#L18)):_

> ``` Ruby
>   resources :tournaments, only: [:create, :index, :edit, :update, :destroy]
> 
>   resources :team_tournament_participations, only: [:create, :destroy]
> ```

What's the different between membership and participation?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/17)_

**Comment by kapone89** [comment]
Reviewed 2 of 39 files at r1.
Review status: 21 of 39 files reviewed at latest revision, 6 unresolved discussions.

---

_[app/controllers/games_controller.rb, line 44 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUMYfGEE2VMO4lYLFRZ:-KUMYfGEE2VMO4lYLFR_:bqnl9cb) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/app/controllers/games_controller.rb#L44)):_

> ``` Ruby
> 
>   def game
>     @game ||= authorize Game.find(params[:id])
> ```

You can use https://github.com/hashrocket/decent_exposure

---

_[app/controllers/matches_controller.rb, line 23 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUM_3fnd1RYTgW4LmXs:-KUM_3fnd1RYTgW4LmXt:bnwjofk) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/app/controllers/matches_controller.rb#L23)):_

> ``` Ruby
> 
>   def edit
>     friendly_match
> ```

I would separate different kinds of matches to different controllera, like FrientlyMatchesController

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/17)_

**Comment by pczarn** [comment]
Review status: 21 of 39 files reviewed at latest revision, 6 unresolved discussions.

---

_[app/controllers/games_controller.rb, line 44 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUMYfGEE2VMO4lYLFRZ:-KURdXsXb7yiwz_qHpSL:bmr01d3) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/app/controllers/games_controller.rb#L44)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> You can use https://github.com/hashrocket/decent_exposure
> </details>
> I'll look into it

---

_[app/controllers/matches_controller.rb, line 23 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUM_3fnd1RYTgW4LmXs:-KURMJfYcK8PuvcJQJPd:b87bqrx) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/app/controllers/matches_controller.rb#L23)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> I would separate different kinds of matches to different controllera, like FrientlyMatchesController
> </details>
> Much better!! But I'll add these changes in another PR, because I have a mess in repo's branches

---

_[app/models/user.rb, line 28 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUMUHQsZi6xwIO7qwef:-KURmUErmxjgrISsuLWu:bkwdi5d) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/app/models/user.rb#L28)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Please improve this regexp.
> </details>
> It's arguable, does this regexp really need to be longer

---

_[app/views/tournament_status_mailer/notify_about_match_result.text.erb, line 5 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUMVLlQXEVOFA_fv9an:-KURiesoIjgmuOG9mIun:b-886gsx) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/app/views/tournament_status_mailer/notify_about_match_result.text.erb#L5)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> I guess you will have 2 blank spaces at the beginning of line.
> </details>
> Fixed

---

_[app/views/tournament_status_mailer/notify_about_match_result.text.erb, line 10 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUMUygGseBYJExclE2J:-KURig9NJO9SDbm9R8KA:b-l3fqpr) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/app/views/tournament_status_mailer/notify_about_match_result.text.erb#L10)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> There should be more information (what match, etc.). And please use "case" here.
> </details>
> Ok. Fixed

---

_[config/routes.rb, line 18 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUMWlO4yKBSRP40qMxg:-KUQzS_Kfise0H60Htsy:bfvf3ku) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/config/routes.rb#L18)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> What's the different between membership and participation?
> </details>
> The former is about a user's membership in a team in a tournament, and the latter is about team participation in a tournament.

Would you agree to rename "team tournament participations" to "teams in tournament", or to "tournament lineups"
But in the case of TeamsInTournament, the whole controller name doesn't end with "s", is that ok?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/17)_

**Comment by kapone89** [comment]
Reviewed 11 of 39 files at r1, 3 of 4 files at r2.
Review status: 34 of 42 files reviewed at latest revision, 7 unresolved discussions.

---

_[app/controllers/matches_controller.rb, line 23 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUM_3fnd1RYTgW4LmXs:-KUSHmRCTyJiK69k6BpK:b32wtd) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/app/controllers/matches_controller.rb#L23)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> Much better!! But I'll add these changes in another PR, because I have a mess in repo's branches
> </details>
> ok

---

_[app/controllers/team_tournament_participations_controller.rb, line 43 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSK2xUaOQq-CV4zm9B:-KUSK2xUaOQq-CV4zm9C:b-6xshp7) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/app/controllers/team_tournament_participations_controller.rb#L43)):_

> ``` Ruby
>   end
> 
>   def added_or_reused_team
> ```

Can you explain the idea of reusing team?

---

_[app/models/match.rb, line 1 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSLBUEYs31YiJDeKuh:-KUSLBUEYs31YiJDeKui:bht0s2v) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/app/models/match.rb#L1)):_

> ``` Ruby
> require "delegate"
> ```

Isn't it required by default?

---

_[app/models/match.rb, line 67 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSKedd_ySrfnn8P9Js:-KUSKedeP5rNNRif-qlK:b31pcs0) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/app/models/match.rb#L67)):_

> ``` Ruby
> end
> 
> class TeamInMatchDecorator < SimpleDelegator
> ```

It should be in separate file.

---

_[app/models/user.rb, line 28 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUMUHQsZi6xwIO7qwef:-KUSFd2ivMymqU1LspVi:bw3lcff) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/app/models/user.rb#L28)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> It's arguable, does this regexp really need to be longer
> </details>
> This regex will allow emails with multiple "@"
> Try this one:
> 
> ```
> /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
> ```

Generally validating email addresses is quite difficult

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/17)_

**Comment by kapone89** [comment]
Reviewed 2 of 39 files at r1, 1 of 4 files at r2.
Review status: 37 of 42 files reviewed at latest revision, 8 unresolved discussions.

---

_[app/services/change_membership_in_tournament.rb, line 57 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSMzFzA-XGRBGxaSWh:-KUSMzG-sa2a0je9VhOe:b-gpcvez) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/app/services/change_membership_in_tournament.rb#L57)):_

> ``` Ruby
>     # for validation, not for saving.
>     tournament.team_tournaments.build(team: new_team)
>     if new_team.member_ids != current_team.member_ids
> ```

Try to use http://www.thechrisoshow.com/2009/02/16/using-guard-clauses-in-your-ruby-code/

---

_[spec/views/tournament_status_mailer/notify_about_match_result.text.erb_spec.rb, line 1 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSNt-QLY3smtKuJG2E:-KUSNt-QLY3smtKuJG2F:b5yemu6) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/spec/views/tournament_status_mailer/notify_about_match_result.text.erb_spec.rb#L1)):_

> ``` Ruby
> require "rails_helper"
> ```

It's the first time I see someone is testing erb view :-) Interesting. Did someone ask you to do that? Usually it's not necesary.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/17)_

**Comment by kapone89** [comment]
Reviewed 1 of 39 files at r1.
Review status: 38 of 42 files reviewed at latest revision, 10 unresolved discussions.

---

_[app/models/tournament.rb, line 45 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSR5Kun_YAj0KFUapF:-KUSR5Kun_YAj0KFUapG:b-alhhhr) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/app/models/tournament.rb#L45)):_

> ``` Ruby
> 
>   def members
>     User.joins(:user_teams).where(user_teams: { team_id: teams.pluck(:id) })
> ```

Try to avoid joins. You can do something like this:

```
has_many :members, through: :teams, class_name: ..., source: ...
```

---

_[app/models/tournament.rb, line 85 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSRoo5OoiXH72776YP:-KUSRoo5OoiXH72776YQ:b-wkwxcm) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/app/models/tournament.rb#L85)):_

> ``` Ruby
> 
>   def related_teams
>     Team.related_to(members.pluck(:id))
> ```

Try to replace related_to method with relation, just like I suggested with members method.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/17)_

**Comment by pczarn** [comment]
Review status: 38 of 42 files reviewed at latest revision, 10 unresolved discussions.

---

_[app/controllers/team_tournament_participations_controller.rb, line 43 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSK2xUaOQq-CV4zm9B:-KUSO_XiHnPR1ottdcvL:br0rb2y) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/app/controllers/team_tournament_participations_controller.rb#L43)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Can you explain the idea of reusing team?
> </details>
> Teams are shared, immutable and unique, so the method must reuse a team if one already exists.

---

_[app/models/match.rb, line 1 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSLBUEYs31YiJDeKuh:-KUSPvq-I9C75jAvmoRL:bn4of29) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/app/models/match.rb#L1)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Isn't it required by default?
> </details>
> Yes it is

---

_[app/models/match.rb, line 67 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSKedd_ySrfnn8P9Js:-KUSPs7OzmSZYQ-V-e93:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/app/models/match.rb#L67)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> It should be in separate file.
> </details>
> Done

---

_[app/models/tournament.rb, line 45 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSR5Kun_YAj0KFUapF:-KUSnRNSieKbvb8YJ0XS:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/app/models/tournament.rb#L45)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Try to avoid joins. You can do something like this:
> 
> ```
> has_many :members, through: :teams, class_name: ..., source: ...
> ```
> 
> </details>
> Done

---

_[app/models/tournament.rb, line 85 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSRoo5OoiXH72776YP:-KUSnLFjWdGfVHHjSTY2:b-5tbp28) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/app/models/tournament.rb#L85)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Try to replace related_to method with relation, just like I suggested with members method.
> </details>
> Done.
> Of three uses of `related_to`, I replaced only this one, because
> the other two have a new object. Looks like such a complex association
> doesn't work on unpersisted objects.

---

_[app/models/user.rb, line 28 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUMUHQsZi6xwIO7qwef:-KUSO9A1F3Mji7sw8yEp:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/app/models/user.rb#L28)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> This regex will allow emails with multiple "@"
> Try this one:
> 
> ```
> /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
> ```
> 
> Generally validating email addresses is quite difficult
> </details>
> Done

---

_[app/services/change_membership_in_tournament.rb, line 57 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSMzFzA-XGRBGxaSWh:-KUSS8TkkszNSbuOrOvN:b-af1erh) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/app/services/change_membership_in_tournament.rb#L57)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Try to use http://www.thechrisoshow.com/2009/02/16/using-guard-clauses-in-your-ruby-code/
> </details>
> Ok, done, but I still try to not use them everywhere

---

_[spec/views/tournament_status_mailer/notify_about_match_result.text.erb_spec.rb, line 1 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSNt-QLY3smtKuJG2E:-KUSRIQRZekp-HUPOd-A:b-95qx5) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/spec/views/tournament_status_mailer/notify_about_match_result.text.erb_spec.rb#L1)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> It's the first time I see someone is testing erb view :-) Interesting. Did someone ask you to do that? Usually it's not necesary.
> </details>
> I thought it's far too easy to leave spaces in a text mail by mistake, so I made this test. I've seen rails automatically generate specs for views.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/17)_

**Comment by kapone89** [comment]
Reviewed 5 of 5 files at r3.
Review status: 40 of 43 files reviewed at latest revision, 5 unresolved discussions.

---

_[app/models/match.rb, line 57 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUvxgH48qLMRufabdFv:-KUvxgH48qLMRufabdFw:bo1wpko) ([raw file](https://github.com/pczarn/gameroom-task/blob/8a8eecbfb5109ad96ccd47b8cc8881dbcef7b6e2/app/models/match.rb#L57)):_

> ``` Ruby
>   end
> 
>   def teams
> ```

Remember to move it to representeron the next step.

---

_[spec/views/tournament_status_mailer/notify_about_match_result.text.erb_spec.rb, line 1 at r2](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUSNt-QLY3smtKuJG2E:-KUvwq6n9qy2kpYqW0Hd:b-88pm3c) ([raw file](https://github.com/pczarn/gameroom-task/blob/5553da8ec945bd3356dd097e1fc2c250f57e4305/spec/views/tournament_status_mailer/notify_about_match_result.text.erb_spec.rb#L1)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> I thought it's far too easy to leave spaces in a text mail by mistake, so I made this test. I've seen rails automatically generate specs for views.
> </details>
> You can leave it, but  I think you can skip views test next time.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/17)_

**Comment by kapone89** [comment]
Reviewed 3 of 39 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[app/controllers/team_tournament_participations_controller.rb, line 49 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUw2yQqs6YmB2fSn-KO:-KUw2yQrWLlvf0MOyDHT:beutzmp) ([raw file](https://github.com/pczarn/gameroom-task/blob/8a8eecbfb5109ad96ccd47b8cc8881dbcef7b6e2/app/controllers/team_tournament_participations_controller.rb#L49)):_

> ``` Ruby
>   def add_or_reuse_team
>     team = Team.new(team_params)
>     reused = Team.related_to(team.member_ids).find { |elem| elem.member_ids == team.member_ids }
> ```
1. When you call member_ids, you can't be sure what the order will be, so it won't always work
2. Try to use SQL instead of find.

---

_[app/services/finish_match.rb, line 53 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUvymaiJiTZkMgae-u8:-KUvymajMvaZIeCL5GGj:bli67ag) ([raw file](https://github.com/pczarn/gameroom-task/blob/8a8eecbfb5109ad96ccd47b8cc8881dbcef7b6e2/app/services/finish_match.rb#L53)):_

> ``` Ruby
>   end
> 
>   def tasks_for_tournament
> ```

Use guard clause

---

_[config/routes.rb, line 18 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUMWlO4yKBSRP40qMxg:-KUw4IPS-0jU6xKVPs2L:bi4y39p) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/config/routes.rb#L18)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> The former is about a user's membership in a team in a tournament, and the latter is about team participation in a tournament.
> 
> Would you agree to rename "team tournament participations" to "teams in tournament", or to "tournament lineups"
> But in the case of TeamsInTournament, the whole controller name doesn't end with "s", is that ok?
> </details>
> so maybe "user tournament membership" and "team tournamnet membership"?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/17)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[app/controllers/team_tournament_participations_controller.rb, line 49 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUw2yQqs6YmB2fSn-KO:-KV-dSKWDAMIbq8EXphl:b-ayyyaz) ([raw file](https://github.com/pczarn/gameroom-task/blob/8a8eecbfb5109ad96ccd47b8cc8881dbcef7b6e2/app/controllers/team_tournament_participations_controller.rb#L49)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> 1. When you call member_ids, you can't be sure what the order will be, so it won't always work
> 2. Try to use SQL instead of find.
>    </details>
>    Done. I will try to use SQL queries later when I change this method

---

_[app/models/match.rb, line 57 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUvxgH48qLMRufabdFv:-KV0KbKH4_HK71mvw8s3:bia1j5f) ([raw file](https://github.com/pczarn/gameroom-task/blob/8a8eecbfb5109ad96ccd47b8cc8881dbcef7b6e2/app/models/match.rb#L57)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Remember to move it to representeron the next step.
> </details>
> MatchTeam takes too much work, so I'll do it later or change nothing

---

_[app/services/finish_match.rb, line 53 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUvymaiJiTZkMgae-u8:-KV-3NzVZjQGO3NDhadk:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/8a8eecbfb5109ad96ccd47b8cc8881dbcef7b6e2/app/services/finish_match.rb#L53)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Use guard clause
> </details>
> Done

---

_[config/routes.rb, line 18 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/17#-KUMWlO4yKBSRP40qMxg:-KV-348Req1byJ1IHex9:bm1ixr4) ([raw file](https://github.com/pczarn/gameroom-task/blob/08042b0979a1f6aed44e9f37c5c7195bcbc0385b/config/routes.rb#L18)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> so maybe "user tournament membership" and "team tournamnet membership"?
> </details>
> I'm going to change it completely later

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/17)_

**Comment by kapone89** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/17)_

**Pull request merged**
