### PR TITLE
Add API with representers

### PR DESCRIPTION
**Pull request by pczarn**
This change is [Reviewable](https://reviewable.io/reviews/pczarn/gameroom-task/18)

### CODE REVIEW

**Comment by kapone89** [comment]
Reviewed 43 of 88 files at r1.
Review status: 43 of 86 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/18)_

**Comment by kapone89** [comment]
Reviewed 4 of 88 files at r1.
Review status: 47 of 86 files reviewed at latest revision, 7 unresolved discussions.

---

_[app/representers/game_representer.rb, line 8 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KUw1tYlT9kFP0JivsO0:-KUw1tYlT9kFP0JivsO1:b-7sxfp3) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/representers/game_representer.rb#L8)):_

> ``` Ruby
>   end
> 
>   def as_json(_ = {})
> ```

basic

---

_[app/representers/games_representer.rb, line 6 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KUw20qMJwa_l8ZPct5i:-KUw20qMJwa_l8ZPct5j:b-7sxfp3) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/representers/games_representer.rb#L6)):_

> ``` Ruby
>   end
> 
>   def as_json(_ = {})
> ```

basic

---

_[app/representers/matches_representer.rb, line 6 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KUw26J9Hh72cChSP0Es:-KUw26J9Hh72cChSP0Et:b-7sxfp3) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/representers/matches_representer.rb#L6)):_

> ``` Ruby
>   end
> 
>   def as_json(_ = {})
> ```

basic

---

_[app/representers/rounds_representer.rb, line 8 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KUw2AkdMWb6H9zz4ZXf:-KUw2AkdMWb6H9zz4ZXg:bmnz539) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/representers/rounds_representer.rb#L8)):_

> ``` Ruby
>   end
> 
>   def flat
> ```

flat, shallow, basic... You know what I mean ;-)

---

_[app/representers/teams_representer.rb, line 8 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KUw05B_DWhnWJAUfYwU:-KUw05Ba_rPIGDpff1vE:bb6037n) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/representers/teams_representer.rb#L8)):_

> ``` Ruby
>   end
> 
>   def shallow(_ = {})
> ```

you can remove params if you are not using them. I guess you need `(_ = {})` only when you are overwriting as_json method, because it can be called with params.

---

_[app/representers/teams_representer.rb, line 8 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KUw0bOaRx1FaFQhKRrk:-KUw0bOaRx1FaFQhKRrl:b-xgr4e6) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/representers/teams_representer.rb#L8)):_

> ``` Ruby
>   end
> 
>   def shallow(_ = {})
> ```

What's the difference between "shallow" and "basic"? Usually, you need representer for each model without nested relations, which you can call either "basic" or "shallow" but don't. I think "basic" is better name.

---

_[app/representers/teams_representer.rb, line 16 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KUw1PXf5prRdWJirBcD:-KUw1PXf5prRdWJirBcE:b-jp5b1i) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/representers/teams_representer.rb#L16)):_

> ``` Ruby
>   end
> 
>   def as_json(_ = {})
> ```

Please move it to the superclass

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/18)_

**Comment by kapone89** [comment]
Review status: 47 of 86 files reviewed at latest revision, 10 unresolved discussions.

---

_[app/controllers/api/v1/games_controller.rb, line 10 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV-CeWc5JDbJ-ChWP_Y:-KV-CeWc5JDbJ-ChWP_Z:b-p0n1hd) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/controllers/api/v1/games_controller.rb#L10)):_

> ``` Ruby
>         game = Game.new(game_params)
>         authorize game
>         game.save!
> ```

No errors handling?

---

_[app/controllers/api/v1/tournaments_controller.rb, line 14 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV-DAAfS4oswPPJBqb8:-KV-DAAfS4oswPPJBqb9:b-p0n1hd) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/controllers/api/v1/tournaments_controller.rb#L14)):_

> ``` Ruby
>       def create
>         tournament = current_user.owned_tournaments.build(tournament_params)
>         tournament.save!
> ```

No errors handling?

---

_[app/controllers/api/v1/tournaments_controller.rb, line 28 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV-DEKHGGXDcHXdtB1_:-KV-DEKHGGXDcHXdtB1a:b-p0n1hd) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/controllers/api/v1/tournaments_controller.rb#L28)):_

> ``` Ruby
> 
>       def destroy
>         @tournament.destroy!
> ```

No errors handling?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/18)_

**Comment by pczarn** [comment]
Review status: 47 of 86 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

_[app/controllers/api/v1/games_controller.rb, line 10 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV-CeWc5JDbJ-ChWP_Y:-KV0TboAqqKnMZTg6oar:b-waptl2) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/controllers/api/v1/games_controller.rb#L10)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> No errors handling?
> </details>
> I added errors handling to `exceptions_handler.rb`, like in Codetunes2.0

---

_[app/representers/rounds_representer.rb, line 8 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KUw2AkdMWb6H9zz4ZXf:-KV0TqWghXZFddvVu8G-:bb7oryy) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/representers/rounds_representer.rb#L8)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> flat, shallow, basic... You know what I mean ;-)
> </details>
> sure

---

_[app/representers/teams_representer.rb, line 8 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KUw05B_DWhnWJAUfYwU:-KV0f0QeGPx71UublFck:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/representers/teams_representer.rb#L8)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> you can remove params if you are not using them. I guess you need `(_ = {})` only when you are overwriting as_json method, because it can be called with params.
> </details>
> Done

---

_[app/representers/teams_representer.rb, line 8 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KUw0bOaRx1FaFQhKRrk:-KV0f1cGDImasIcgKFqI:bb6un1j) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/representers/teams_representer.rb#L8)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> What's the difference between "shallow" and "basic"? Usually, you need representer for each model without nested relations, which you can call either "basic" or "shallow" but don't. I think "basic" is better name.
> </details>
> Done

---

_[app/representers/teams_representer.rb, line 16 at r1](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KUw1PXf5prRdWJirBcD:-KV0f3LQAeQh19pCMags:bdd2hgn) ([raw file](https://github.com/pczarn/gameroom-task/blob/2ca72dc65edbd051b60125e660ae3a503fd1f4bd/app/representers/teams_representer.rb#L16)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Please move it to the superclass
> </details>
> Done, moved to BaseRepresenter

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/18)_

**Comment by kapone89** [comment]
Reviewed 1 of 88 files at r1, 13 of 16 files at r2, 2 of 4 files at r3.
Review status: 63 of 89 files reviewed at latest revision, 6 unresolved discussions.

---

_[app/representers/round_representer.rb, line 12 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5sFwib2IU9FRhXodX:-KV5sFwjm1BKOBH-OqQH:b-14nhzo) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/representers/round_representer.rb#L12)):_

> ``` Ruby
>   end
> 
>   def with_number
> ```

maybe with_mathces ?

---

_[app/representers/rounds_representer.rb, line 9 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5sQPuoeapcykdpIpO:-KV5sQPuoeapcykdpIpP:bmyx3wi) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/representers/rounds_representer.rb#L9)):_

> ``` Ruby
> 
>   def basic
>     rounds.sort_by(&:number).map { |round| RoundRepresenter.new(round).basic }
> ```

I think you should sort in controller/repository

---

_[app/representers/tournament_representer.rb, line 18 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5sxrMR3RX8rT3lOTk:-KV5sxrMR3RX8rT3lOTl:b-rqc87m) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/representers/tournament_representer.rb#L18)):_

> ``` Ruby
>       game_id: tournament.game_id,
>       owner_id: tournament.owner_id,
>       rounds: RoundsRepresenter.new(tournament.rounds).basic,
> ```

basic representer should not have nested relations

---

_[app/representers/tournaments_representer.rb, line 13 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5tIl855Sy6JvjyKig:-KV5tIl855Sy6JvjyKih:b5sr9q1) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/representers/tournaments_representer.rb#L13)):_

> ``` Ruby
> 
>   def with_permissions(current_user)
>     basic.map { |tournament| tournament.with_permissions(current_user) }
> ```

tournaments, not basic (I guess)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/18)_

**Comment by kapone89** [comment]
Reviewed 20 of 88 files at r1, 3 of 16 files at r2, 2 of 4 files at r3.
Review status: 86 of 89 files reviewed at latest revision, 7 unresolved discussions.

---

_[app/controllers/api/v1/matches_controller.rb, line 8 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5u4AsqjXrkujbkWGI:-KV5u4AsqjXrkujbkWGJ:b-5qtw73) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/controllers/api/v1/matches_controller.rb#L8)):_

> ``` Ruby
> 
>       def create
>         match = current_user.owned_matches.build(friendly_match_params)
> ```

U can use create! instead of build & save!

---

_[app/controllers/api/v1/users_controller.rb, line 24 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5ucnAT2pSpUiuDc2r:-KV5ucnAT2pSpUiuDc2s:brh8cxy) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/controllers/api/v1/users_controller.rb#L24)):_

> ``` Ruby
>       private
> 
>       def load_user
> ```

please fetch the same as in other controllers

---

_[app/representers/match_representer.rb, line 23 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5vJX28meTYp6x2MSC:-KV5vJX28meTYp6x2MSD:b-nuv3nx) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/representers/match_representer.rb#L23)):_

> ``` Ruby
>   def with_winner
>     basic.merge(
>       winner: match.winning_team.id == match.team_one_id ? 0 : 1,
> ```

Returning 0/1 is not a good idea. Why not return entire team?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/18)_

**Comment by pczarn** [comment]
Review status: 86 of 89 files reviewed at latest revision, 7 unresolved discussions.

---

_[app/controllers/api/v1/users_controller.rb, line 24 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5ucnAT2pSpUiuDc2r:-KV6-zqgW1NXqvtkfUh5:b-886gsx) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/controllers/api/v1/users_controller.rb#L24)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> please fetch the same as in other controllers
> </details>
> Fixed

---

_[app/representers/match_representer.rb, line 23 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5vJX28meTYp6x2MSC:-KV5yLCDjaWgchSZLZKn:byiywhs) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/representers/match_representer.rb#L23)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Returning 0/1 is not a good idea. Why not return entire team?
> </details>
> Better not return entire team to simplify code in the frontend. It uses IDs instead of nested records in responses. So I will return the ID here.

---

_[app/representers/round_representer.rb, line 12 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5sFwib2IU9FRhXodX:-KV5yriLB2mirJNR8yqM:b5b4vqy) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/representers/round_representer.rb#L12)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> maybe with_mathces ?
> </details>
> Fixed: `basic` returns matches, too. So I'm removing this one. It's not used.

---

_[app/representers/rounds_representer.rb, line 9 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5sQPuoeapcykdpIpO:-KV5z-QNI9h8kNHZu490:bq3xxwo) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/representers/rounds_representer.rb#L9)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> I think you should sort in controller/repository
> </details>
> I'm not sure, the representation is only valid when rounds are sorted by number. Maybe the repository should put matches in an array, with `tournament.rounds.sort_by(&:number).map { |round| round.matches }`

---

_[app/representers/tournament_representer.rb, line 18 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5sxrMR3RX8rT3lOTk:-KV6-qVQn5QlLv38HA5K:b-886gsx) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/representers/tournament_representer.rb#L18)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> basic representer should not have nested relations
> </details>
> Fixed

---

_[app/representers/tournaments_representer.rb, line 13 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5tIl855Sy6JvjyKig:-KV6-rSv8HOxbanqSlBq:b-886gsx) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/representers/tournaments_representer.rb#L13)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> tournaments, not basic (I guess)
> </details>
> Fixed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/18)_

**Comment by pczarn** [comment]
Review status: 86 of 89 files reviewed at latest revision, 7 unresolved discussions.

---

_[app/controllers/api/v1/matches_controller.rb, line 8 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5u4AsqjXrkujbkWGI:-KV62Cs94zjmYz0_fUpx:b-1m1wcp) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/controllers/api/v1/matches_controller.rb#L8)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> U can use create! instead of build & save!
> </details>
> Ok, done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/18)_

**Comment by kapone89** [comment]
Reviewed 1 of 88 files at r1, 7 of 7 files at r4.
Review status: 87 of 89 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/18)_

**Comment by kapone89** [comment]
Reviewed 2 of 88 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[app/representers/rounds_representer.rb, line 9 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5sQPuoeapcykdpIpO:-KVZpC39Rh5hd70qskcQ:bpb1l8d) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/representers/rounds_representer.rb#L9)):_
<details><summary>

<i>Previously, pczarn (Piotr Czarnecki) wrote…</i></summary>



> I'm not sure, the representation is only valid when rounds are sorted by number. Maybe the repository should put matches in an array, with `tournament.rounds.sort_by(&:number).map { |round| round.matches }`
> </details>
> Representer should not change the order of objects. In this case you should sort rounds in TournamentRepresenter.

---

_[spec/spec_helper.rb, line 35 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KVZrc79TwBIwLaZI9Ge:-KVZrc79TwBIwLaZI9Gf:b-siau1z) ([raw file](https://github.com/pczarn/gameroom-task/blob/4f5b000e680eb65de864e8869e26d804ef24c824/spec/spec_helper.rb#L35)):_

> ``` Ruby
>   # Speed up hashing
>   config.before(:each) do
>     PASS ||= "password".freeze
> ```

I think constants are not necessary here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/18)_

**Comment by pczarn** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[app/representers/rounds_representer.rb, line 9 at r3](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KV5sQPuoeapcykdpIpO:-KVa0QJP5zOcdknskhsg:b-1m1wcp) ([raw file](https://github.com/pczarn/gameroom-task/blob/0b051486400c4956dd75b3bebf71e051b5c8281a/app/representers/rounds_representer.rb#L9)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> Representer should not change the order of objects. In this case you should sort rounds in TournamentRepresenter.
> </details>
> Ok, done

---

_[spec/spec_helper.rb, line 35 at r4](https://reviewable.io:443/reviews/pczarn/gameroom-task/18#-KVZrc79TwBIwLaZI9Ge:-KVa0Rpw_eykL8v-8Red:b-5gtosb) ([raw file](https://github.com/pczarn/gameroom-task/blob/4f5b000e680eb65de864e8869e26d804ef24c824/spec/spec_helper.rb#L35)):_
<details><summary>

<i>Previously, kapone89 (Tomasz Kapłon) wrote…</i></summary>



> I think constants are not necessary here.
> </details>
> Which constants do you mean? The second one, `PASS_HASHED`, is important

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/18)_

**Comment by kapone89** [comment]
Reviewed 3 of 3 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pczarn/gameroom-task/18)_

**Pull request merged**
